/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

public interface MtcAnzConstants {
  public final static int INVALIDID = -1;
  public final static int ZOK = 0;
  public final static int ZFAILED = 1;
  public final static int MTC_EBASE_CP = 0xE000;
  public final static int MTC_EBASE_REG = 0xE100;
  public final static int MTC_EBASE_CALL = 0xE200;
  public final static int MTC_EBASE_VSHARE = 0xE300;
  public final static int MTC_EBASE_CAP = 0xE400;
  public final static int MTC_EBASE_BUDDY = 0xE500;
  public final static int MTC_EBASE_GRP = 0xE600;
  public final static int MTC_EBASE_CONF = 0xE700;
  public final static int MTC_EBASE_GS = 0xE800;
  public final static int MTC_EBASE_PRES = 0xE900;
  public final static int MTC_EBASE_IM = 0xEA00;
  public final static int MTC_EBASE_CONTACT = 0xEB00;
  public final static int MTC_EBASE_LOG = 0xEC00;
  public final static int MTC_EBASE_LCS = 0xED00;
}
