/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

public class MtcByteArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MtcByteArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MtcByteArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MtcVerJNI.delete_MtcByteArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData(SWIGTYPE_p_void value) {
    MtcVerJNI.MtcByteArray_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData() {
    long cPtr = MtcVerJNI.MtcByteArray_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setSize(long value) {
    MtcVerJNI.MtcByteArray_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return MtcVerJNI.MtcByteArray_size_get(swigCPtr, this);
  }

  public void setValue(byte[] value) {
    MtcVerJNI.MtcByteArray_value_set(swigCPtr, this, value);
  }

  public byte[] getValue() {
    return MtcVerJNI.MtcByteArray_value_get(swigCPtr, this);
  }

  public MtcByteArray() {
    this(MtcVerJNI.new_MtcByteArray(), true);
  }

}
