/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

public class MtcCallDbJNI {
    public final static void MtcNumber_value_set(long jarg1, MtcNumber jarg1_, int jarg2) {

    }

    public final static int MtcNumber_value_get(long jarg1, MtcNumber jarg1_) {
        return 0;
    }

    public final static long new_MtcNumber() {
        return 0;

    }

    public final static void delete_MtcNumber(long jarg1) {

    }

    public final static void MtcByteArray_data_set(long jarg1, MtcByteArray jarg1_, long jarg2) {

    }

    public final static long MtcByteArray_data_get(long jarg1, MtcByteArray jarg1_) {
        return 0;

    }

    public final static void MtcByteArray_size_set(long jarg1, MtcByteArray jarg1_, long jarg2) {

    }

    public final static long MtcByteArray_size_get(long jarg1, MtcByteArray jarg1_) {
        return 0;

    }

    public final static void MtcByteArray_value_set(long jarg1, MtcByteArray jarg1_, byte[] jarg2) {

    }

    public final static byte[] MtcByteArray_value_get(long jarg1, MtcByteArray jarg1_) {
        return null;
    }

    public final static long new_MtcByteArray() {
        return 0;

    }

    public final static void delete_MtcByteArray(long jarg1) {

    }

    public final static void MtcString_value_set(long jarg1, MtcString jarg1_, String jarg2) {

    }

    public final static String MtcString_value_get(long jarg1, MtcString jarg1_) {
        return null;
    }

    public final static long new_MtcString() {
        return 0;

    }

    public final static void delete_MtcString(long jarg1) {

    }

    public final static int Mtc_CallDbGetDtmfType() {
        return 0;

    }

    public final static int Mtc_CallDbSetDtmfType(int jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbGetDtmfPayload() {
        return 0;

    }

    public final static int Mtc_CallDbSetDtmfPayload(int jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetDtmfWatch() {
        return false;
    }

    public final static int Mtc_CallDbSetDtmfWatch(boolean jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbGetAudioQos(MtcNumber jarg1, MtcNumber jarg2, MtcNumber jarg3, MtcNumber jarg4) {
        return 0;

    }

    public final static int Mtc_CallDbSetAudioQos(boolean jarg1, boolean jarg2, boolean jarg3, boolean jarg4) {
        return 0;

    }

    public final static int Mtc_CallDbSetAecEnable(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetAecEnable() {
        return false;
    }

    public final static int Mtc_CallDbSetAecMode(short jarg1) {
        return 0;

    }

    public final static short Mtc_CallDbGetAecMode() {
        return 0;

    }

    public final static int Mtc_CallDbSetVadEnable(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetVadEnable() {
        return false;
    }

    public final static int Mtc_CallDbSetVadMode(short jarg1) {
        return 0;

    }

    public final static short Mtc_CallDbGetVadMode() {
        return 0;

    }

    public final static int Mtc_CallDbSetAgcEnable(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetAgcEnable() {
        return false;
    }

    public final static int Mtc_CallDbSetAgcMode(short jarg1) {
        return 0;

    }

    public final static short Mtc_CallDbGetAgcMode() {
        return 0;

    }

    public final static int Mtc_CallDbSetAgcTarget(short jarg1) {
        return 0;

    }

    public final static short Mtc_CallDbGetAgcTarget() {
        return 0;

    }

    public final static int Mtc_CallDbSetRxAgcEnable(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetRxAgcEnable() {
        return false;

    }

    public final static int Mtc_CallDbSetRxAgcMode(short jarg1) {
        return 0;

    }

    public final static short Mtc_CallDbGetRxAgcMode() {
        return 0;

    }

    public final static int Mtc_CallDbSetRxAgcTarget(short jarg1) {
        return 0;

    }

    public final static short Mtc_CallDbGetRxAgcTarget() {
        return 0;

    }

    public final static int Mtc_CallDbSetAnrEnable(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetAnrEnable() {
        return false;
    }

    public final static int Mtc_CallDbSetAnrMode(short jarg1) {
        return 0;

    }

    public final static short Mtc_CallDbGetAnrMode() {
        return 0;

    }

    public final static int Mtc_CallDbSetRxAnrEnable(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetRxAnrEnable() {
        return false;
    }

    public final static int Mtc_CallDbSetRxAnrMode(short jarg1) {
        return 0;

    }

    public final static short Mtc_CallDbGetRxAnrMode() {
        return 0;

    }

    public final static int Mtc_CallDbSetAudioRed(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetAudioRed() {
        return false;
    }

    public final static int Mtc_CallDbGetSuptAudioCodecCount() {
        return 0;

    }

    public final static String Mtc_CallDbGetSuptAudioCodec(int jarg1) {
        return null;
    }

    public final static int Mtc_CallDbGetAudioCodecCount() {
        return 0;

    }

    public final static String Mtc_CallDbGetAudioCodecByPriority(short jarg1) {
        return null;
    }

    public final static int Mtc_CallDbSetAudioCodecEnable(String jarg1, boolean jarg2) {
        return 0;

    }

    public final static int Mtc_CallDbSetAudioCodecByPriority(String jarg1, short jarg2) {
        return 0;

    }

    public final static int Mtc_CallDbGetAudioDevice(MtcString jarg1, MtcString jarg2) {
        return 0;

    }

    public final static int Mtc_CallDbSetAudioDevice(String jarg1, String jarg2) {
        return 0;

    }

    public final static int Mtc_CallDbGetSpkDftVol() {
        return 0;

    }

    public final static int Mtc_CallDbSetSpkDftVol(int jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbGetSuptVideoCodecCount() {
        return 0;

    }

    public final static String Mtc_CallDbGetSuptVideoCodec(int jarg1) {
        return null;
    }

    public final static int Mtc_CallDbGetVideoCodecCount() {
        return 0;

    }

    public final static String Mtc_CallDbGetVideoCodecByPriority(short jarg1) {
        return null;
    }

    public final static int Mtc_CallDbSetVideoCodecEnable(String jarg1, boolean jarg2) {
        return 0;

    }

    public final static int Mtc_CallDbSetVideoCodecByPriority(String jarg1, short jarg2) {
        return 0;

    }

    public final static String Mtc_CallDbGetVideoDevice() {
        return null;
    }

    public final static int Mtc_CallDbSetVideoDevice(String jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbGetVideoBitrate() {
        return 0;

    }

    public final static int Mtc_CallDbSetVideoBitrate(int jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbGetVideoFramerate() {
        return 0;

    }

    public final static int Mtc_CallDbSetVideoFramerate(int jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbSetVideoH264Profile(short jarg1) {
        return 0;

    }

    public final static short Mtc_CallDbGetVideoH264Profile() {
        return 0;

    }

    public final static int Mtc_CallDbSetVideoH264PayloadType(int jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbGetVideoH264PayloadType() {
        return 0;

    }

    public final static int Mtc_CallDbGetVideoResolution(MtcNumber jarg1, MtcNumber jarg2) {
        return 0;

    }

    public final static int Mtc_CallDbSetVideoResolution(int jarg1, int jarg2) {
        return 0;

    }

    public final static String Mtc_CallDbGetVideoResolutionX() {
        return null;
    }

    public final static int Mtc_CallDbSetVideoResolutionX(String jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetMdmEnable() {
        return false;
    }

    public final static int Mtc_CallDbSetMdmEnable(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetResolutionControl() {
        return false;
    }

    public final static int Mtc_CallDbSetResolutionControl(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetFramerateControl() {
        return false;
    }

    public final static int Mtc_CallDbSetFramerateControl(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetCpuLoadControl() {
        return false;
    }

    public final static int Mtc_CallDbSetCpuLoadControl(boolean jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbGetCpuLoadTarget() {
        return 0;

    }

    public final static int Mtc_CallDbSetCpuLoadTarget(int jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetFir() {
        return false;
    }

    public final static int Mtc_CallDbSetFir(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetFirByInfo() {
        return false;
    }

    public final static int Mtc_CallDbSetFirByInfo(boolean jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbGetKeyPeriod() {
        return 0;

    }

    public final static int Mtc_CallDbSetKeyPeriod(int jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetVideoBem() {
        return false;
    }

    public final static int Mtc_CallDbSetVideoBem(boolean jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbGetVideoBandwidth(MtcNumber jarg1, MtcNumber jarg2) {
        return 0;

    }

    public final static int Mtc_CallDbSetVideoBandwidth(int jarg1, int jarg2) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetVideoOrientSend() {
        return false;
    }

    public final static int Mtc_CallDbSetVideoOrientSend(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetVideoOrientRecv() {
        return false;
    }

    public final static int Mtc_CallDbSetVideoOrientRecv(boolean jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbGetVideoOrientId() {
        return 0;

    }

    public final static int Mtc_CallDbSetVideoOrientId(int jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetVideoArs() {
        return false;
    }

    public final static int Mtc_CallDbSetVideoArs(boolean jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbSetArsMode(short jarg1) {
        return 0;

    }

    public final static short Mtc_CallDbGetArsMode() {
        return 0;

    }

    public final static int Mtc_CallDbGetVideoArsParm(MtcNumber jarg1, MtcNumber jarg2, MtcNumber jarg3, MtcNumber jarg4) {
        return 0;

    }

    public final static int Mtc_CallDbSetVideoArsParm(int jarg1, int jarg2, int jarg3, int jarg4) {
        return 0;

    }

    public final static int Mtc_CallDbSetVideoArsParmX(boolean jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbSetVideoRedFec(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetVideoRedFec() {
        return false;
    }

    public final static boolean Mtc_CallDbGetRtcpEnable() {
        return false;
    }

    public final static int Mtc_CallDbSetRtcpEnable(boolean jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbGetRtpPort(MtcNumber jarg1, MtcNumber jarg2, MtcNumber jarg3, MtcNumber jarg4) {
        return 0;

    }

    public final static int Mtc_CallDbSetRtpPort(int jarg1, int jarg2, int jarg3, int jarg4) {
        return 0;

    }

    public final static int Mtc_CallDbGetRtpBreakTime() {
        return 0;

    }

    public final static int Mtc_CallDbSetRtpBreakTime(int jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbGetSrtpCryptoType() {
        return 0;

    }

    public final static int Mtc_CallDbSetSrtpCryptoType(int jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetSrtpAuthRtp() {
        return false;
    }

    public final static int Mtc_CallDbSetSrtpAuthRtp(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetSrtpEncryptRtp() {
        return false;
    }

    public final static int Mtc_CallDbSetSrtpEncryptRtp(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetSrtpEncryptRtcp() {
        return false;
    }

    public final static int Mtc_CallDbSetSrtpEncryptRtcp(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetNackEnable() {
        return false;
    }

    public final static int Mtc_CallDbSetNackEnable(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetTmmbrEnable() {
        return false;
    }

    public final static int Mtc_CallDbSetTmmbrEnable(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetAudioRtcpMuxEnable() {
        return false;
    }

    public final static int Mtc_CallDbSetAudioRtcpMuxEnable(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetAudioArsEnable() {
        return false;
    }

    public final static int Mtc_CallDbSetAudioArsEnable(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetVideoRtcpMuxEnable() {
        return false;
    }

    public final static int Mtc_CallDbSetVideoRtcpMuxEnable(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetRpsiEnable() {
        return false;
    }

    public final static int Mtc_CallDbSetRpsiEnable(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetSmallNaluEnable() {
        return false;
    }

    public final static int Mtc_CallDbSetSmallNaluEnable(boolean jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbGetPtime() {
        return 0;

    }

    public final static int Mtc_CallDbSetPtime(int jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbGetBandwidthCt() {
        return 0;

    }

    public final static int Mtc_CallDbSetBandwidthCt(int jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbGetBandwidthAs() {
        return 0;

    }

    public final static int Mtc_CallDbSetBandwidthAs(int jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetAutoAcptCall() {
        return false;
    }

    public final static int Mtc_CallDbSetAutoAcptCall(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetCwc() {
        return false;
    }

    public final static int Mtc_CallDbSetCwc(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetDoNotDisturb() {
        return false;
    }

    public final static int Mtc_CallDbSetDoNotDisturb(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetCfuInfo(MtcString jarg1) {
        return false;
    }

    public final static int Mtc_CallDbSetCfuInfo(boolean jarg1, String jarg2) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetCfbInfo(MtcString jarg1) {
        return false;
    }

    public final static int Mtc_CallDbSetCfbInfo(boolean jarg1, String jarg2) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetCfnaInfo(MtcString jarg1, MtcNumber jarg2) {
        return false;
    }

    public final static int Mtc_CallDbSetCfnaInfo(boolean jarg1, String jarg2, int jarg3) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetPrivacyOpt(short jarg1) {
        return false;
    }

    public final static int Mtc_CallDbSetPrivacyOpt(short jarg1, boolean jarg2) {
        return 0;

    }

    public final static boolean Mtc_CallDbGetAsymNego() {
        return false;
    }

    public final static int Mtc_CallDbSetAsymNego(boolean jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbGetSessTmrInfo(MtcNumber jarg1, MtcNumber jarg2, MtcNumber jarg3) {
        return 0;

    }

    public final static int Mtc_CallDbSetSessTmrInfo(int jarg1, int jarg2, int jarg3) {
        return 0;

    }

    public final static String Mtc_CallDbGetPrefixCont() {
        return null;
    }

    public final static int Mtc_CallDbSetPrefixCont(String jarg1) {
        return 0;

    }

    public final static int Mtc_CallDbGetPrefixOption() {
        return 0;

    }

    public final static int Mtc_CallDbSetPrefixOption(int jarg1) {
        return 0;

    }
}
