/**
 * @file MtcCliCfgConstants.java
 * @brief MtcCliCfgConstants constants
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

/**
 * @brief MtcCliCfgConstants constants
 */
public interface MtcCliCfgConstants {
  public final static int INVALIDID = -1; /**< @brief invalid id */
  public final static int ZOK = 0; /**< @brief ok */
  public final static int ZFAILED = 1; /**< @brief failed */
  public final static int MTC_REG_CAP_OPT_NULL = 0; /**< @brief no capability. */
  public final static int MTC_REG_CAP_OPT_QVAL = 1; /**< @brief qvalue */
  public final static int MTC_REG_CAP_OPT_CS_VOICE = 2; /**< @brief 3GPP cs voice */
  public final static int MTC_REG_CAP_OPT_MMTEL = 3; /**< @brief IMS MMTel */
  public final static int MTC_REG_CAP_OPT_ISHARE = 4; /**< @brief IMS Image Share */
  public final static int MTC_REG_CAP_OPT_IM = 5; /**< @brief OMA IM */
  public final static int MTC_REG_CAP_OPT_IM_LMSG = 6; /**< @brief OMA Large Message  */
  public final static int MTC_REG_CAP_OPT_RCS_CS = 7; /**< @brief RCS cs telephony */
  public final static int MTC_REG_CAP_OPT_RCS_GEO = 8; /**< @brief RCS geopush */
  public final static int MTC_REG_CAP_OPT_RCSE_IM = 9; /**< @brief RCSE file transfer */
  public final static int MTC_REG_CAP_OPT_RCSE_FT = 10; /**< @brief RCSE file transfer */
  public final static int MTC_REG_CAP_OPT_AUDIO = 11; /**< @brief audio */
  public final static int MTC_REG_CAP_OPT_VIDEO = 12; /**< @brief video */
  public final static long MTC_REG_CAP_OPT_ALL = -1; /**< @brief all capabilties. */
}
