/**
 * @file MtcCliDbConstants.java
 * @brief MtcCliDbConstants constants
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

/**
 * @brief MtcCliDbConstants constants
 */
public interface MtcCliDbConstants {
  public final static int INVALIDID = -1; /**< @brief invalid id */
  public final static int ZOK = 0; /**< @brief ok */
  public final static int ZFAILED = 1; /**< @brief failed */
  // EN_MTC_REG_SRV_TYPE 
  public final static int EN_MTC_REG_SRV_VOIP = 0; /**< @brief voip service */
  public final static int EN_MTC_REG_SRV_MMTEL = EN_MTC_REG_SRV_VOIP + 1; /**< @brief 3GPP IMS service */
  public final static int EN_MTC_REG_SRV_VOLTE = EN_MTC_REG_SRV_MMTEL + 1; /**< @brief 3GPP VoLTE service */

  // EN_MTC_TPT_TYPE 
  public final static int EN_MTC_TPT_UDP = 0; /**< @brief UDP transport */
  public final static int EN_MTC_TPT_TCP = EN_MTC_TPT_UDP + 1; /**< @brief TCP transport */

  // EN_MTC_ACC_NET_TYPE 
  public final static int EN_MTC_ACC_NET_UNKNOWN = 0; /**< @brief unknown */
  public final static int EN_MTC_ACC_NET_IEEE_802_11 = EN_MTC_ACC_NET_UNKNOWN + 1; /**< @brief IEEE-802.11 */
  public final static int EN_MTC_ACC_NET_IEEE_802_11A = EN_MTC_ACC_NET_IEEE_802_11 + 1; /**< @brief IEEE-802.11a". */
  public final static int EN_MTC_ACC_NET_IEEE_802_11B = EN_MTC_ACC_NET_IEEE_802_11A + 1; /**< @brief IEEE-802.11b". */
  public final static int EN_MTC_ACC_NET_IEEE_802_11G = EN_MTC_ACC_NET_IEEE_802_11B + 1; /**< @brief IEEE-802.11g */
  public final static int EN_MTC_ACC_NET_IEEE_802_11N = EN_MTC_ACC_NET_IEEE_802_11G + 1; /**< @brief IEEE-802.11n */
  public final static int EN_MTC_ACC_NET_3GPP_GERAN = EN_MTC_ACC_NET_IEEE_802_11N + 1; /**< @brief 3GPP-GERAN". */
  public final static int EN_MTC_ACC_NET_3GPP_UTRAN_FDD = EN_MTC_ACC_NET_3GPP_GERAN + 1; /**< @brief 3GPP-UTRAN-FDD". */
  public final static int EN_MTC_ACC_NET_3GPP_UTRAN_TDD = EN_MTC_ACC_NET_3GPP_UTRAN_FDD + 1; /**< @brief 3GPP-UTRAN-TDD". */
  public final static int EN_MTC_ACC_NET_3GPP_E_UTRAN_FDD = EN_MTC_ACC_NET_3GPP_UTRAN_TDD + 1; /**< @brief 3GPP-E-UTRAN-FDD */
  public final static int EN_MTC_ACC_NET_3GPP_E_UTRAN_TDD = EN_MTC_ACC_NET_3GPP_E_UTRAN_FDD + 1; /**< @brief 3GPP-E-UTRAN-TDD */
  public final static int EN_MTC_ACC_NET_3GPP_UTRAN = EN_MTC_ACC_NET_3GPP_E_UTRAN_TDD + 1; /**< @brief 3GPP-UTRAN */
  public final static int EN_MTC_ACC_NET_3GPP_E_UTRAN = EN_MTC_ACC_NET_3GPP_UTRAN + 1; /**< @brief 3GPP-E-UTRAN */
  public final static int EN_MTC_ACC_NET_3GPP_WLAN = EN_MTC_ACC_NET_3GPP_E_UTRAN + 1; /**< @brief 3GPP-WLAN */
  public final static int EN_MTC_ACC_NET_3GPP_GAN = EN_MTC_ACC_NET_3GPP_WLAN + 1; /**< @brief 3GPP-GAN */
  public final static int EN_MTC_ACC_NET_3GPP_HSPA = EN_MTC_ACC_NET_3GPP_GAN + 1; /**< @brief 3GPP-HSPA */
  public final static int EN_MTC_ACC_NET_3GPP_CDMA2000 = EN_MTC_ACC_NET_3GPP_HSPA + 1; /**< @brief 3GPP-CDMA2000". */
  public final static int EN_MTC_ACC_NET_3GPP2_1X = EN_MTC_ACC_NET_3GPP_CDMA2000 + 1; /**< @brief 3GPP2-1X */
  public final static int EN_MTC_ACC_NET_3GPP2_1X_FEMTO = EN_MTC_ACC_NET_3GPP2_1X + 1; /**< @brief 3GPP2-1X-Femto */
  public final static int EN_MTC_ACC_NET_3GPP2_1X_HRPD = EN_MTC_ACC_NET_3GPP2_1X_FEMTO + 1; /**< @brief 3GPP2-1X-HRPD */
  public final static int EN_MTC_ACC_NET_3GPP2_UMB = EN_MTC_ACC_NET_3GPP2_1X_HRPD + 1; /**< @brief 3GPP2-UMB */
  public final static int EN_MTC_ACC_NET_ADSL = EN_MTC_ACC_NET_3GPP2_UMB + 1; /**< @brief ADSL */
  public final static int EN_MTC_ACC_NET_ADSL2 = EN_MTC_ACC_NET_ADSL + 1; /**< @brief ADSL2 */
  public final static int EN_MTC_ACC_NET_ADSL2X = EN_MTC_ACC_NET_ADSL2 + 1; /**< @brief ADSL2+ */
  public final static int EN_MTC_ACC_NET_RADSL = EN_MTC_ACC_NET_ADSL2X + 1; /**< @brief RADSL */
  public final static int EN_MTC_ACC_NET_SDSL = EN_MTC_ACC_NET_RADSL + 1; /**< @brief SDSL */
  public final static int EN_MTC_ACC_NET_HDSL = EN_MTC_ACC_NET_SDSL + 1; /**< @brief HDSL */
  public final static int EN_MTC_ACC_NET_HDSL2 = EN_MTC_ACC_NET_HDSL + 1; /**< @brief HDSL2 */
  public final static int EN_MTC_ACC_NET_G_SHDSL = EN_MTC_ACC_NET_HDSL2 + 1; /**< @brief G.SHDSL */
  public final static int EN_MTC_ACC_NET_VDSL = EN_MTC_ACC_NET_G_SHDSL + 1; /**< @brief VDSL */
  public final static int EN_MTC_ACC_NET_IDSL = EN_MTC_ACC_NET_VDSL + 1; /**< @brief IDSL */
  public final static int EN_MTC_ACC_NET_IEEE_802_3 = EN_MTC_ACC_NET_IDSL + 1; /**< @brief IEEE-802.3 */
  public final static int EN_MTC_ACC_NET_IEEE_802_3A = EN_MTC_ACC_NET_IEEE_802_3 + 1; /**< @brief IEEE-802.3a */
  public final static int EN_MTC_ACC_NET_IEEE_802_3E = EN_MTC_ACC_NET_IEEE_802_3A + 1; /**< @brief IEEE-802.3e */
  public final static int EN_MTC_ACC_NET_IEEE_802_3I = EN_MTC_ACC_NET_IEEE_802_3E + 1; /**< @brief IEEE-802.3i */
  public final static int EN_MTC_ACC_NET_IEEE_802_3J = EN_MTC_ACC_NET_IEEE_802_3I + 1; /**< @brief IEEE-802.3j */
  public final static int EN_MTC_ACC_NET_IEEE_802_3U = EN_MTC_ACC_NET_IEEE_802_3J + 1; /**< @brief IEEE-802.3u */
  public final static int EN_MTC_ACC_NET_IEEE_802_3AB = EN_MTC_ACC_NET_IEEE_802_3U + 1; /**< @brief IEEE-802.3ab */
  public final static int EN_MTC_ACC_NET_IEEE_802_3AE = EN_MTC_ACC_NET_IEEE_802_3AB + 1; /**< @brief IEEE-802.3ae */
  public final static int EN_MTC_ACC_NET_IEEE_802_3AK = EN_MTC_ACC_NET_IEEE_802_3AE + 1; /**< @brief IEEE-802.3ak */
  public final static int EN_MTC_ACC_NET_IEEE_802_3AQ = EN_MTC_ACC_NET_IEEE_802_3AK + 1; /**< @brief IEEE-802.3aq */
  public final static int EN_MTC_ACC_NET_IEEE_802_3AN = EN_MTC_ACC_NET_IEEE_802_3AQ + 1; /**< @brief IEEE-802.3an */
  public final static int EN_MTC_ACC_NET_IEEE_802_3Y = EN_MTC_ACC_NET_IEEE_802_3AN + 1; /**< @brief IEEE-802.3y */
  public final static int EN_MTC_ACC_NET_IEEE_802_3Z = EN_MTC_ACC_NET_IEEE_802_3Y + 1; /**< @brief IEEE-802.3z */
  public final static int EN_MTC_ACC_NET_GPON = EN_MTC_ACC_NET_IEEE_802_3Z + 1; /**< @brief GPON */
  public final static int EN_MTC_ACC_NET_XGPON1 = EN_MTC_ACC_NET_GPON + 1; /**< @brief XGPON1 */
  public final static int EN_MTC_ACC_NET_GSTN = EN_MTC_ACC_NET_XGPON1 + 1; /**< @brief GSTN */

  // EN_MTC_IMS_AUTH_TYPE 
  public final static int EN_MTC_IMS_AUTH_UNKNOWN = 0; /**< @brief unknown */
  public final static int EN_MTC_IMS_AUTH_EARLY_IMS = EN_MTC_IMS_AUTH_UNKNOWN + 1; /**< @brief Early IMS */
  public final static int EN_MTC_IMS_AUTH_IMS_AKA = EN_MTC_IMS_AUTH_EARLY_IMS + 1; /**< @brief IMS AKA */
  public final static int EN_MTC_IMS_AUTH_SIP_DIGEST = EN_MTC_IMS_AUTH_IMS_AKA + 1; /**< @brief SIP DIGEST (without TLS) */

  // EN_MTC_URI_FMT_TYPE 
  public final static int EN_MTC_URI_FMT_TEL = 0; /**< @brief tel uri */
  public final static int EN_MTC_URI_FMT_SIP = EN_MTC_URI_FMT_TEL + 1; /**< @brief sip uri */

  // EN_MTC_NAT_TRAVERSAL_TYPE 
  public final static int EN_MTC_NAT_TRAVERSAL_OFF = 0; /* not use Nat Traversal */
  public final static int EN_MTC_NAT_TRAVERSAL_STUN = EN_MTC_NAT_TRAVERSAL_OFF + 1; /* using STUN */
  public final static int EN_MTC_NAT_TRAVERSAL_TURN = EN_MTC_NAT_TRAVERSAL_STUN + 1; /* using TURN */
  public final static int EN_MTC_NAT_TRAVERSAL_ICE = EN_MTC_NAT_TRAVERSAL_TURN + 1; /* using ICE */
  public final static int EN_MTC_NAT_TRAVERSAL_MPT = EN_MTC_NAT_TRAVERSAL_ICE + 1; /* using MPT */

}
