/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

public class MtcCliDbJNI {
    public final static void MtcNumber_value_set(long jarg1, MtcNumber jarg1_, int jarg2) {

    }

    public final static int MtcNumber_value_get(long jarg1, MtcNumber jarg1_) {
        return 0;
    }

    public final static long new_MtcNumber() {
        return 0;

    }

    public final static void delete_MtcNumber(long jarg1) {

    }

    public final static void MtcByteArray_data_set(long jarg1, MtcByteArray jarg1_, long jarg2) {

    }

    public final static long MtcByteArray_data_get(long jarg1, MtcByteArray jarg1_) {
        return 0;

    }

    public final static void MtcByteArray_size_set(long jarg1, MtcByteArray jarg1_, long jarg2) {

    }

    public final static long MtcByteArray_size_get(long jarg1, MtcByteArray jarg1_) {
        return 0;

    }

    public final static void MtcByteArray_value_set(long jarg1, MtcByteArray jarg1_, byte[] jarg2) {

    }

    public final static byte[] MtcByteArray_value_get(long jarg1, MtcByteArray jarg1_) {
        return null;
    }

    public final static long new_MtcByteArray() {
        return 0;

    }

    public final static void delete_MtcByteArray(long jarg1) {

    }

    public final static void MtcString_value_set(long jarg1, MtcString jarg1_, String jarg2) {

    }

    public final static String MtcString_value_get(long jarg1, MtcString jarg1_) {
        return null;
    }

    public final static long new_MtcString() {
        return 0;

    }

    public final static void delete_MtcString(long jarg1) {

    }

    public final static int Mtc_CliDbApplyAll() {
        return 0;

    }

    public final static boolean Mtc_CliDbGetApplyChange() {
        return false;
    }

    public final static int Mtc_CliDbSetApplyChange(boolean jarg1) {
        return 0;

    }

    public final static String Mtc_CliDbGetLocalIp() {
        return null;
    }

    public final static int Mtc_CliDbGetLocalIpX() {
        return 0;

    }

    public final static int Mtc_CliDbSetLocalIp(String jarg1) {
        return 0;

    }

    public final static boolean Mtc_CliDbGetLogOpen() {
        return false;
    }

    public final static int Mtc_CliDbSetLogOpen(boolean jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetLogLevel() {
        return 0;

    }

    public final static int Mtc_CliDbSetLogLevel(int jarg1) {
        return 0;

    }

    public final static String Mtc_CliDbGetUserName() {
        return null;
    }

    public final static int Mtc_CliDbSetUserName(String jarg1) {
        return 0;

    }

    public final static String Mtc_CliDbGetNickName() {
        return null;
    }

    public final static int Mtc_CliDbSetNickName(String jarg1) {
        return 0;

    }

    public final static String Mtc_CliDbGetAuthName() {
        return null;
    }

    public final static int Mtc_CliDbSetAuthName(String jarg1) {
        return 0;

    }

    public final static String Mtc_CliDbGetAuthPass() {
        return null;
    }

    public final static int Mtc_CliDbSetAuthPass(String jarg1) {
        return 0;

    }

    public final static String Mtc_CliDbGetPhoneContext() {
        return null;
    }

    public final static int Mtc_CliDbSetPhoneContext(String jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetAuthType() {
        return 0;

    }

    public final static int Mtc_CliDbSetAuthType(int jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetRoamType() {
        return 0;

    }

    public final static int Mtc_CliDbSetRoamType(int jarg1) {
        return 0;

    }

    public final static boolean Mtc_CliDbGetRegNoDigest() {
        return false;
    }

    public final static int Mtc_CliDbSetRegNoDigest(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_CliDbGetSuptHeartbeat() {
        return false;
    }

    public final static int Mtc_CliDbSetSuptHeartbeat(boolean jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetHeartbeatTmr() {
        return 0;

    }

    public final static int Mtc_CliDbSetHeartbeatTmr(int jarg1) {
        return 0;

    }

    public final static boolean Mtc_CliDbGetUserReg() {
        return false;
    }

    public final static int Mtc_CliDbSetUserReg(boolean jarg1) {
        return 0;

    }

    public final static String Mtc_CliDbGetSipRegIp() {
        return null;
    }

    public final static int Mtc_CliDbSetSipRegIp(String jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetRegExpire() {
        return 0;

    }

    public final static int Mtc_CliDbSetRegExpire(int jarg1) {
        return 0;

    }

    public final static short Mtc_CliDbGetSipRegTpt() {
        return 0;

    }

    public final static int Mtc_CliDbSetSipRegTpt(short jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetSipRegUdpPort() {
        return 0;

    }

    public final static int Mtc_CliDbSetSipRegUdpPort(int jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetSipRegTcpPort() {
        return 0;

    }

    public final static int Mtc_CliDbSetSipRegTcpPort(int jarg1) {
        return 0;

    }

    public final static String Mtc_CliDbGetSipRegRealm() {
        return null;
    }

    public final static int Mtc_CliDbSetSipRegRealm(String jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetDnsLclPort() {
        return 0;

    }

    public final static int Mtc_CliDbSetDnsLclPort(int jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetDnsServIp(boolean jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbSetDnsServIp(boolean jarg1, int jarg2) {
        return 0;

    }

    public final static int Mtc_CliDbGetDnsServPort(boolean jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbSetDnsServPort(boolean jarg1, int jarg2) {
        return 0;

    }

    public final static int Mtc_CliDbGetNatTraversalMode() {
        return 0;

    }

    public final static int Mtc_CliDbSetNatTraversalMode(int jarg1) {
        return 0;

    }

    public final static String Mtc_CliDbGetStunServerName() {
        return null;
    }

    public final static int Mtc_CliDbSetStunServerName(String jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetStunServerPort() {
        return 0;

    }

    public final static int Mtc_CliDbSetStunServerPort(int jarg1) {
        return 0;

    }

    public final static boolean Mtc_CliDbGetStunServerSupportTurn() {
        return false;
    }

    public final static int Mtc_CliDbSetStunServerSupportTurn(boolean jarg1) {
        return 0;

    }

    public final static String Mtc_CliDbGetMdmServerAddress() {
        return null;
    }

    public final static int Mtc_CliDbSetMdmServerAddress(String jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetMdmServerPort() {
        return 0;

    }

    public final static int Mtc_CliDbSetMdmServerPort(int jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetSipLclUdpPort() {
        return 0;

    }

    public final static int Mtc_CliDbSetSipLclUdpPort(int jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetSipLclTcpPort() {
        return 0;

    }

    public final static int Mtc_CliDbSetSipLclTcpPort(int jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetSipTmr1() {
        return 0;

    }

    public final static int Mtc_CliDbSetSipTmr1(int jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetSipTmr2() {
        return 0;

    }

    public final static int Mtc_CliDbSetSipTmr2(int jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetSipTmr4() {
        return 0;

    }

    public final static int Mtc_CliDbSetSipTmr4(int jarg1) {
        return 0;

    }

    public final static boolean Mtc_CliDbGetUseIpv4() {
        return false;
    }

    public final static boolean Mtc_CliDbGetUseTelUri() {
        return false;
    }

    public final static int Mtc_CliDbSetUseTelUri(boolean jarg1) {
        return 0;

    }

    public final static String Mtc_CliDbGetSipServIp(boolean jarg1) {
        return null;
    }

    public final static int Mtc_CliDbSetSipServIp(boolean jarg1, String jarg2) {
        return 0;

    }

    public final static int Mtc_CliDbGetSipServPort(boolean jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbSetSipServPort(boolean jarg1, int jarg2) {
        return 0;

    }

    public final static int Mtc_CliDbGetSipServPortX(boolean jarg1, short jarg2) {
        return 0;

    }

    public final static int Mtc_CliDbSetSipServPortX(boolean jarg1, short jarg2, int jarg3) {
        return 0;

    }

    public final static short Mtc_CliDbGetSipServTpt(boolean jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbSetSipServTpt(boolean jarg1, short jarg2) {
        return 0;

    }

    public final static String Mtc_CliDbGetSipServRealm(boolean jarg1) {
        return null;
    }

    public final static int Mtc_CliDbSetSipServRealm(boolean jarg1, String jarg2) {
        return 0;

    }

    public final static int Mtc_CliDbGetRegSrvType() {
        return 0;

    }

    public final static int Mtc_CliDbSetRegSrvType(int jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetRegRetryCount() {
        return 0;

    }

    public final static int Mtc_CliDbSetRegRetryCount(int jarg1) {
        return 0;

    }

    public final static boolean Mtc_CliDbGetSubsRegEvnt() {
        return false;
    }

    public final static int Mtc_CliDbSetSubsRegEvnt(boolean jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetAccNetType() {
        return 0;

    }

    public final static int Mtc_CliDbSetAccNetType(int jarg1) {
        return 0;

    }

    public final static String Mtc_CliDbGetAccNetInfo() {
        return null;
    }

    public final static int Mtc_CliDbSetAccNetInfo(String jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetNatUriFmt() {
        return 0;

    }

    public final static int Mtc_CliDbGetIntUriFmt() {
        return 0;

    }

    public final static String Mtc_CliDbGetSipInstance() {
        return null;
    }

    public final static String Mtc_CliDbGetQValue() {
        return null;
    }

    public final static String Mtc_CliDbGetAcvServAddr() {
        return null;
    }

    public final static int Mtc_CliDbSetAcvServAddr(String jarg1) {
        return 0;

    }

    public final static String Mtc_CliDbGetAcvUrl() {
        return null;
    }

    public final static int Mtc_CliDbSetAcvUrl(String jarg1) {
        return 0;

    }

    public final static int Mtc_CliDbGetAcvServPort() {
        return 0;

    }

    public final static int Mtc_CliDbSetAcvServPort(int jarg1) {
        return 0;

    }
}
