/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

public class MtcCallJNI {
    public final static void MtcNumber_value_set(long jarg1, MtcNumber jarg1_, int jarg2) {

    }

    public final static int MtcNumber_value_get(long jarg1, MtcNumber jarg1_) {
        return 0;

    }

    public final static long new_MtcNumber() {
        return 0;

    }

    public final static void delete_MtcNumber(long jarg1) {

    }

    public final static void MtcByteArray_data_set(long jarg1, MtcByteArray jarg1_, long jarg2) {

    }

    public final static long MtcByteArray_data_get(long jarg1, MtcByteArray jarg1_) {
        return 0;

    }

    public final static void MtcByteArray_size_set(long jarg1, MtcByteArray jarg1_, long jarg2) {

    }

    public final static long MtcByteArray_size_get(long jarg1, MtcByteArray jarg1_) {
        return 0;

    }

    public final static void MtcByteArray_value_set(long jarg1, MtcByteArray jarg1_, byte[] jarg2) {

    }

    public final static byte[] MtcByteArray_value_get(long jarg1, MtcByteArray jarg1_) {
        return null;
    }

    public final static long new_MtcByteArray() {
        return 0;

    }

    public final static void delete_MtcByteArray(long jarg1) {

    }

    public final static void MtcString_value_set(long jarg1, MtcString jarg1_, String jarg2) {

    }

    public final static String MtcString_value_get(long jarg1, MtcString jarg1_) {
        return null;
    }

    public final static long new_MtcString() {
        return 0;

    }

    public final static void delete_MtcString(long jarg1) {

    }

    public final static int Mtc_SessCall(String jarg1, Object jarg2, boolean jarg3, boolean jarg4) {
        return 0;

    }

    public final static int Mtc_SessCallX(String jarg1, Object jarg2, boolean jarg3, boolean jarg4, boolean jarg5, boolean jarg6) {
        return 0;

    }

    public final static int Mtc_SessAlert(int jarg1, Object jarg2, int jarg3, boolean jarg4) {
        return 0;

    }

    public final static int Mtc_SessAnswer(int jarg1, Object jarg2, boolean jarg3, boolean jarg4) {
        return 0;

    }

    public final static int Mtc_SessTerm(int jarg1, int jarg2, String jarg3) {
        return 0;

    }

    public final static int Mtc_SessHold(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessUnhold(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessUTrsf(int jarg1, String jarg2) {
        return 0;

    }

    public final static int Mtc_SessATrsf(int jarg1, int jarg2) {
        return 0;

    }

    public final static int Mtc_SessDiv(int jarg1, String jarg2) {
        return 0;

    }

    public final static int Mtc_SessUpdate(int jarg1, boolean jarg2, boolean jarg3) {
        return 0;

    }

    public final static int Mtc_SessUpdateRsp(int jarg1, boolean jarg2, boolean jarg3) {
        return 0;

    }

    public final static int Mtc_SessPickUp(String jarg1, String jarg2, Object jarg3, boolean jarg4, boolean jarg5) {
        return 0;

    }

    public final static int Mtc_SessPickUpX(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessDtmf(int jarg1, int jarg2) {
        return 0;

    }

    public final static int Mtc_SessInfo(int jarg1, String jarg2) {
        return 0;

    }

    public final static int Mtc_SessPreviewSetArea(int jarg1, Object jarg2, short jarg3, short jarg4, int jarg5, int jarg6) {
        return 0;

    }

    public final static int Mtc_SessPreviewShow(int jarg1, boolean jarg2) {
        return 0;

    }

    public final static int Mtc_SessCameraAttach(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessCameraDetach(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessRenderReset(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessRenderAdd(int jarg1, Object jarg2, short jarg3, short jarg4, int jarg5, int jarg6) {
        return 0;

    }

    public final static int Mtc_SessRenderBuild(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessRenderRelease(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessVideoStart(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessVideoStop(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessVideoPause(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessVideoResume(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessGetVideoSize(int jarg1, MtcNumber jarg2, MtcNumber jarg3) {
        return 0;

    }

    public final static int Mtc_SessGetVideoRemoteSize(int jarg1, MtcNumber jarg2, MtcNumber jarg3) {
        return 0;

    }

    public final static int Mtc_SessGetVideoLocalSize(int jarg1, MtcNumber jarg2, MtcNumber jarg3) {
        return 0;
    }

    public final static boolean Mtc_SessHasVideo(int jarg1) {
        return false;

    }

    public final static boolean Mtc_SessHasAudio(int jarg1) {
        return false;

    }

    public final static boolean Mtc_SessHasTalk(int jarg1) {
        return false;

    }

    public final static boolean Mtc_SessHasHold(int jarg1) {
        return false;

    }

    public final static boolean Mtc_SessHasHeld(int jarg1) {
        return false;

    }

    public final static int Mtc_SessAudioLostRatio(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessVideoLostRatio(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessAudioLostCount(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessVideoLostCount(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessAudioRtt(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessVideoRtt(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessAudioJitter(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessVideoJitter(int jarg1) {
        return 0;

    }

    public final static boolean Mtc_SessPeerOfferVideo(int jarg1) {
        return false;

    }

    public final static boolean Mtc_SessPeerOfferAudio(int jarg1) {
        return false;

    }

    public final static boolean Mtc_SessGetMicMute(int jarg1) {
        return false;
    }

    public final static int Mtc_SessSetMicMute(int jarg1, boolean jarg2) {
        return 0;

    }

    public final static float Mtc_SessGetMicScale(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessSetMicScale(int jarg1, float jarg2) {
        return 0;

    }

    public final static boolean Mtc_SessGetSpkMute(int jarg1) {
        return false;
    }

    public final static int Mtc_SessSetSpkMute(int jarg1, boolean jarg2) {
        return 0;

    }

    public final static float Mtc_SessGetSpkScale(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessSetSpkScale(int jarg1, float jarg2) {
        return 0;

    }

    public final static int Mtc_SessGetSpkVol(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessSetSpkVol(int jarg1, int jarg2) {
        return 0;

    }

    public final static boolean Mtc_SessGetMixVoice(int jarg1) {
        return false;
    }

    public final static int Mtc_SessSetMixVoice(int jarg1, boolean jarg2) {
        return 0;

    }

    public final static int Mtc_SessRotateRemote(int jarg1, int jarg2) {
        return 0;

    }

    public final static int Mtc_SessRotateLocal(int jarg1, int jarg2) {
        return 0;
    }

    public final static Object Mtc_SessGetCookie(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessSetCookie(int jarg1, Object jarg2) {
        return 0;

    }

    public final static int Mtc_SessGetCallId(int jarg1, MtcString jarg2) {
        return 0;

    }

    public final static int Mtc_SessGetPeerUri(int jarg1, MtcString jarg2, MtcString jarg3) {
        return 0;

    }

    public final static int Mtc_SessGetPeerId(int jarg1, MtcString jarg2, MtcString jarg3) {
        return 0;

    }

    public final static boolean Mtc_SessPeerIsFocus(int jarg1) {
        return false;
    }

    public final static boolean Mtc_SessHasOfferAnswer(int jarg1) {
        return false;
    }

    public final static int Mtc_SessGetAlertInfo(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessGetEarlyMediaStatus(int jarg1, boolean jarg2) {
        return 0;

    }

    public final static int Mtc_SessRecMicStart(String jarg1, short jarg2) {
        return 0;

    }

    public final static int Mtc_SessRecMicStop() {
        return 0;

    }

    public final static int Mtc_SessRecPlayStart(int jarg1, String jarg2, short jarg3) {
        return 0;

    }

    public final static int Mtc_SessRecPlayStop(int jarg1) {
        return 0;

    }

    public final static int Mtc_SessRecCallStart(String jarg1, short jarg2) {
        return 0;

    }

    public final static int Mtc_SessRecCallStop() {
        return 0;

    }

    public final static int Mtc_SessRecSndStart(int jarg1, String jarg2, short jarg3, int jarg4) {
        return 0;

    }

    public final static int Mtc_SessRecSndStop(int jarg1) {
        return 0;

    }

    public final static String Mtc_SessGetAudioStat(int jarg1) {
        return null;
    }

    public final static String Mtc_SessGetVideoStat(int jarg1) {
        return null;
    }

    public final static int Mtc_SessSetRxAgcEnable(int jarg1, boolean jarg2) {
        return 0;

    }

    public final static int Mtc_SessGetRxAgcEnable(int jarg1, MtcNumber jarg2) {
        return 0;

    }

    public final static int Mtc_SessSetRxAgcMode(int jarg1, short jarg2) {
        return 0;

    }

    public final static int Mtc_SessGetRxAgcMode(int jarg1, MtcNumber jarg2) {
        return 0;

    }

    public final static int Mtc_SessSetRxAgcTarget(int jarg1, int jarg2) {
        return 0;

    }

    public final static int Mtc_SessGetRxAgcTarget(int jarg1, MtcNumber jarg2) {
        return 0;

    }

    public final static int Mtc_SessSetRxAnrEnable(int jarg1, boolean jarg2) {
        return 0;

    }

    public final static int Mtc_SessGetRxAnrEnable(int jarg1, MtcNumber jarg2) {
        return 0;

    }

    public final static int Mtc_SessSetRxAnrMode(int jarg1, short jarg2) {
        return 0;

    }

    public final static int Mtc_SessGetRxAnrMode(int jarg1, MtcNumber jarg2) {
        return 0;

    }

    public final static int Mtc_SessSetVadEnable(int jarg1, boolean jarg2) {
        return 0;

    }

    public final static int Mtc_SessGetVadEnable(int jarg1, MtcNumber jarg2) {
        return 0;

    }

    public final static int Mtc_SessSetVadMode(int jarg1, short jarg2) {
        return 0;

    }

    public final static int Mtc_SessGetVadMode(int jarg1, MtcNumber jarg2) {
        return 0;

    }

    public final static int Mtc_SessEnhanceColor(int jarg1, boolean jarg2) {

        return 0;
    }

    public final static int Mtc_SessArsEnableCpuCtrl(int jarg1, boolean jarg2) {

        return 0;
    }

    public final static int Mtc_SessArsSetCupCtrlTgt(int jarg1, int jarg2) {

        return 0;
    }

    public final static int Mtc_SessArsEnableBem(int jarg1, boolean jarg2) {

        return 0;
    }

    public final static int Mtc_SessArsGetVideoBitrate(int jarg1, MtcNumber jarg2) {

        return 0;
    }

    public final static int Mtc_SessArsSetVideoBitrate(int jarg1, int jarg2) {

        return 0;
    }

    public final static int Mtc_SessRecRecvVideoStart(int jarg1, String jarg2, short jarg3, int jarg4, int jarg5, boolean jarg6) {

        return 0;
    }

    public final static int Mtc_SessRecRecvVideoStop(int jarg1) {

        return 0;
    }

    public final static int Mtc_SessRecSendVideoStart(int jarg1, String jarg2, short jarg3, int jarg4, int jarg5, boolean jarg6) {

        return 0;
    }

    public final static int Mtc_SessRecSendVideoStop(int jarg1) {

        return 0;
    }

    public final static int Mtc_SessRenderSnapshot(int jarg1, String jarg2) {
        return 0;

    }

    public final static int Mtc_SessCaptureSnapshot(int jarg1, String jarg2) {
        return 0;
    }

    public final static String Mtc_SessGetStatDesc(int jarg1) {
        return null;
    }
}
