/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

public class MtcMediaJNI {
    public final static void MtcNumber_value_set(long jarg1, MtcNumber jarg1_, int jarg2) {

    }

    public final static int MtcNumber_value_get(long jarg1, MtcNumber jarg1_) {
        return 0;

    }

    public final static long new_MtcNumber() {
        return 0;

    }

    public final static void delete_MtcNumber(long jarg1) {

    }

    public final static void MtcByteArray_data_set(long jarg1, MtcByteArray jarg1_, long jarg2) {

    }

    public final static long MtcByteArray_data_get(long jarg1, MtcByteArray jarg1_) {
        return 0;

    }

    public final static void MtcByteArray_size_set(long jarg1, MtcByteArray jarg1_, long jarg2) {

    }

    public final static long MtcByteArray_size_get(long jarg1, MtcByteArray jarg1_) {
        return 0;

    }

    public final static void MtcByteArray_value_set(long jarg1, MtcByteArray jarg1_, byte[] jarg2) {

    }

    public final static byte[] MtcByteArray_value_get(long jarg1, MtcByteArray jarg1_) {
        return null;
    }

    public final static long new_MtcByteArray() {
        return 0;

    }

    public final static void delete_MtcByteArray(long jarg1) {

    }

    public final static void MtcString_value_set(long jarg1, MtcString jarg1_, String jarg2) {

    }

    public final static String MtcString_value_get(long jarg1, MtcString jarg1_) {
        return null;
    }

    public final static long new_MtcString() {
        return 0;

    }

    public final static void delete_MtcString(long jarg1) {

    }

    public final static void ST_MTC_RECT_iX_set(long jarg1, ST_MTC_RECT jarg1_, int jarg2) {

    }

    public final static int ST_MTC_RECT_iX_get(long jarg1, ST_MTC_RECT jarg1_) {
        return 0;

    }

    public final static void ST_MTC_RECT_iY_set(long jarg1, ST_MTC_RECT jarg1_, int jarg2) {

    }

    public final static int ST_MTC_RECT_iY_get(long jarg1, ST_MTC_RECT jarg1_) {
        return 0;

    }

    public final static void ST_MTC_RECT_iWidth_set(long jarg1, ST_MTC_RECT jarg1_, int jarg2) {

    }

    public final static int ST_MTC_RECT_iWidth_get(long jarg1, ST_MTC_RECT jarg1_) {
        return 0;

    }

    public final static void ST_MTC_RECT_iHeight_set(long jarg1, ST_MTC_RECT jarg1_, int jarg2) {

    }

    public final static int ST_MTC_RECT_iHeight_get(long jarg1, ST_MTC_RECT jarg1_) {
        return 0;

    }

    public final static long new_ST_MTC_RECT() {
        return 0;

    }

    public final static void delete_ST_MTC_RECT(long jarg1) {

    }

    public final static String Mtc_AudioGetInputDev() {
        return null;

    }

    public final static int Mtc_AudioSetInputDev(String jarg1) {
        return 0;

    }

    public final static int Mtc_AudioGetInputDevCnt() {
        return 0;

    }

    public final static String Mtc_AudioEnumInputDev(int jarg1) {
        return null;

    }

    public final static int Mtc_AudioGetInputStreamType() {
        return 0;

    }

    public final static int Mtc_AudioSetInputVol(int jarg1) {
        return 0;

    }

    public final static int Mtc_AudioGetInputVol() {
        return 0;

    }

    public final static int Mtc_AudioMuteInput(boolean jarg1) {
        return 0;

    }

    public final static int Mtc_AudioMuteInputX(boolean jarg1) {
        return 0;

    }

    public final static boolean Mtc_AudioIsMuteInputX() {
        return false;
    }

    public final static String Mtc_AudioGetOutputDev() {
        return null;

    }

    public final static int Mtc_AudioSetOutputDev(String jarg1) {
        return 0;

    }

    public final static int Mtc_AudioGetOutputDevCnt() {
        return 0;

    }

    public final static String Mtc_AudioEnumOutputDev(int jarg1) {
        return null;

    }

    public final static int Mtc_AudioGetOutputStreamType() {
        return 0;

    }

    public final static int Mtc_AudioSetOutputVol(int jarg1) {
        return 0;

    }

    public final static int Mtc_AudioGetOutputVol() {
        return 0;

    }

    public final static int Mtc_AudioMuteOutput(boolean jarg1) {
        return 0;

    }

    public final static String Mtc_VideoGetInputDev() {
        return null;
    }

    public final static int Mtc_VideoSetInputDev(String jarg1) {
        return 0;

    }

    public final static int Mtc_VideoGetInputDevCnt() {
        return 0;

    }

    public final static String Mtc_VideoEnumInputDev(int jarg1) {
        return null;
    }

    public final static int Mtc_VideoRotateCamera(int jarg1) {
        return 0;

    }

    public final static int Mtc_VideoGetCamCapCnt() {
        return 0;

    }

    public final static int Mtc_VideoGetCamCap(int jarg1, MtcNumber jarg2, MtcNumber jarg3, MtcNumber jarg4) {
        return 0;

    }

    public final static int Mtc_VideoCalcRect(int jarg1, long jarg2, ST_MTC_RECT jarg2_, long jarg3, ST_MTC_RECT jarg3_) {
        return 0;

    }

    public final static int Mtc_VideoCalcRectX(int jarg1, long jarg2, ST_MTC_RECT jarg2_, long jarg3, ST_MTC_RECT jarg3_, long jarg4, ST_MTC_RECT jarg4_) {
        return 0;
    }

    public final static boolean Mtc_VideoCheckFormat(String jarg1) {
        return false;
    }
}
