/**
 * @file MtcProvDb.java
 * @brief MtcProvDb interface
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

/**
 * @brief MtcProvDb interface
 */
public class MtcProvDb implements MtcProvDbConstants {
/**
 * @brief Flush provision into database.
 *
 * @retval ZOK Set the flush successfully.
 * @retval ZFAILED Set the flush failed.
 */
  public static int Mtc_ProvDbFlush() {
    return MtcProvDbJNI.Mtc_ProvDbFlush();
  }

/**
 * @brief Get the automatically start on PC option from database.
 *
 * @return Automatically start on PC option.
 */
  public static boolean Mtc_ProvDbGetLoginOnPC() {
    return MtcProvDbJNI.Mtc_ProvDbGetLoginOnPC();
  }

/**
 * @brief Get the using manual local IP option from database.
 *
 * @return Automatically start on PC option.
 */
  public static boolean Mtc_ProvDbGetManualIp() {
    return MtcProvDbJNI.Mtc_ProvDbGetManualIp();
  }

/**
 * @brief Get the GUI show debug window option from database.
 *
 * @return Show debug window option.
 */
  public static boolean Mtc_ProvDbGetGuiShowDbg() {
    return MtcProvDbJNI.Mtc_ProvDbGetGuiShowDbg();
  }

/**
 * @brief Get the MME dump debug option from database.
 *
 * @return MME dump debug option.
 */
  public static boolean Mtc_ProvDbGetMmeDumpDbg() {
    return MtcProvDbJNI.Mtc_ProvDbGetMmeDumpDbg();
  }

/**
 * @brief Get the MME log level from database.
 *
 * @return MME log level number.
 */
  public static short Mtc_ProvDbGetMmeLogLevel() {
    return MtcProvDbJNI.Mtc_ProvDbGetMmeLogLevel();
  }

/**
 * @brief Get the mvc record voice option from database.
 *
 * @return mvc record debug option.
 */
  public static boolean Mtc_ProvDbGetMvcRecVoice() {
    return MtcProvDbJNI.Mtc_ProvDbGetMvcRecVoice();
  }

/**
 * @brief Get the mvd record video option from database.
 *
 * @return mvd record debug option.
 */
  public static boolean Mtc_ProvDbGetMvdRecVideo() {
    return MtcProvDbJNI.Mtc_ProvDbGetMvdRecVideo();
  }

/**
 * @brief Get the mvd sync audio option from database.
 *
 * @return mvc record debug option.
 */
  public static boolean Mtc_ProvDbGetMvdSyncAudio() {
    return MtcProvDbJNI.Mtc_ProvDbGetMvdSyncAudio();
  }

/**
 * @brief Get the current profile user from database.
 *
 * @return Current profile user.
 */
  public static String Mtc_ProvDbGetCurProfUser() {
    return MtcProvDbJNI.Mtc_ProvDbGetCurProfUser();
  }

/**
 * @brief Get emergency server realm.
 *
 * The general emergency call flow is like below:
 * -# No any account has logined
 * -# initialize the client
 * -# Mtc_CliInit(profile director);
 * -# initialize callback functions
 * -# mtcCliCbPrint(print callback);
 * -# mtcCallCbAlerted(alerted callback);
 * -# mtcCallCbTalking(talking callback);
 * -# mtcCallCbTermed(terminated callback);
 * -# mtcCallCbError(error callback);
 * -# Open an null account Mtc_CliOpen(ZNULL)
 * -# Start client service Mtc_CliStart()
 * -# Get Emergency server info by @ref MtcProvDb::Mtc_ProvDbGetEmgAddr
 * -# Set local and server parameters:
 * @code
   Mtc_CliDbSetSipLclTcpPort(5060);
   Mtc_CliDbSetSipLclTcpPort(5060);
   Mtc_CliDbSetSipRegIp(pcProxyAddr);
   Mtc_CliDbSetSipRegPort(5060);
   Mtc_CliDbSetSipRegRealm(pcProxyRealm);
   Mtc_CliDbSetSipRegTpt(EN_MSP_TPT_UDP);
   Mtc_CliDbSetUserReg(true);
   Mtc_CliDbSetAuthName("unknown");
   Mtc_CliDbSetAuthPass("unknown");
 * @endcode
 *
 * @return Default emergency server realm.
 */
  public static String Mtc_ProvDbGetEmgRealm() {
    return MtcProvDbJNI.Mtc_ProvDbGetEmgRealm();
  }

/**
 * @brief Get the emergency server address from database.
 *
 * @return Default emergency server address.
 */
  public static String Mtc_ProvDbGetEmgAddr() {
    return MtcProvDbJNI.Mtc_ProvDbGetEmgAddr();
  }

/**
 * @brief Get the default register realm from database.
 *
 * @return Default register realm.
 */
  public static String Mtc_ProvDbGetDftRegRealm() {
    return MtcProvDbJNI.Mtc_ProvDbGetDftRegRealm();
  }

/**
 * @brief Get the default proxy address from database.
 *
 * @return Default proxy address.
 */
  public static String Mtc_ProvDbGetDftProxyAddr() {
    return MtcProvDbJNI.Mtc_ProvDbGetDftProxyAddr();
  }

/**
 * @brief Get the default authentication name in register realm from database.
 *
 * @return Default authentication name in realm.
 */
  public static boolean Mtc_ProvDbGetDftAuthNameInRealm() {
    return MtcProvDbJNI.Mtc_ProvDbGetDftAuthNameInRealm();
  }

/**
 * @brief Get the default subscribe register event from database.
 *
 * @return Default subscribe register event.
 */
  public static boolean Mtc_ProvDbGetDftSubRegEvnt() {
    return MtcProvDbJNI.Mtc_ProvDbGetDftSubRegEvnt();
  }

/**
 * @brief Get the default DTMF type from database.
 *
 * @return Default DTMF type, see @ref MtcCallDbConstants::EN_MTC_DB_DTMF_AUTO.
 */
  public static int Mtc_ProvDbGetDftDtmfType() {
    return MtcProvDbJNI.Mtc_ProvDbGetDftDtmfType();
  }

/**
 * @brief Get the default ring directory.
 *
 * @return Default ring directory.
 */
  public static String Mtc_ProvDbGetDftRingDir() {
    return MtcProvDbJNI.Mtc_ProvDbGetDftRingDir();
  }

/**
 * @brief Get ring mute option.
 *
 * @retval true Mute ring.
 * @retval false Not to mute ring.
 *
 * @see MtcProvDb::Mtc_ProvDbSetRingMute
 */
  public static boolean Mtc_ProvDbGetRingMute() {
    return MtcProvDbJNI.Mtc_ProvDbGetRingMute();
  }

/**
 * @brief Get the default temporary directory.
 *
 * @return Default temporary directory.
 */
  public static String Mtc_ProvDbGetTempDir() {
    return MtcProvDbJNI.Mtc_ProvDbGetTempDir();
  }

/**
 * @brief Set automatically start on PC option.
 *
 * @param [in] bEnable The boolean value.
 *
 * @retval ZOK Set the option successfully.
 * @retval ZFAILED Set the option failed.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetLoginOnPC
 */
  public static int Mtc_ProvDbSetLoginOnPC(boolean bEnable) {
    return MtcProvDbJNI.Mtc_ProvDbSetLoginOnPC(bEnable);
  }

/**
 * @brief Set using manual local IP option.
 *
 * @param [in] bEnable The boolean value.
 *
 * @retval ZOK Set the option successfully.
 * @retval ZFAILED Set the option failed.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetManualIp
 */
  public static int Mtc_ProvDbSetManualIp(boolean bEnable) {
    return MtcProvDbJNI.Mtc_ProvDbSetManualIp(bEnable);
  }

/**
 * @brief Set MME dump information to file option.
 *
 * @param [in] bEnable The boolean value.
 *
 * @retval ZOK Set the option successfully.
 * @retval ZFAILED Set the option failed.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetMmeDumpDbg
 */
  public static int Mtc_ProvDbSetMmeDumpDbg(boolean bEnable) {
    return MtcProvDbJNI.Mtc_ProvDbSetMmeDumpDbg(bEnable);
  }

/**
 * @brief Set MME log level.
 *
 * @param [in] ucLevel Log level number, 0 is no log, bigger number for more log.
 *
 * @retval ZOK Set the option successfully.
 * @retval ZFAILED Set the option failed.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetMmeDumpDbg
 */
  public static int Mtc_ProvDbSetMmeLogLevel(short ucLevel) {
    return MtcProvDbJNI.Mtc_ProvDbSetMmeLogLevel(ucLevel);
  }

/**
 * @brief Set current profile user.
 *
 * @param [in] pcUser The profile user name.
 *
 * @retval ZOK Set the profile user successfully.
 * @retval ZFAILED Set the profile user failed.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetCurProfUser
 */
  public static int Mtc_ProvDbSetCurProfUser(String pcUser) {
    return MtcProvDbJNI.Mtc_ProvDbSetCurProfUser(pcUser);
  }

/**
 * @brief Set default ring directory.
 *
 * @param [in] pcDir The default ring directory.
 *
 * @retval ZOK Set the default ring directory successfully.
 * @retval ZFAILED Set the default ring directory failed.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetDftRingDir
 */
  public static int Mtc_ProvDbSetDftRingDir(String pcDir) {
    return MtcProvDbJNI.Mtc_ProvDbSetDftRingDir(pcDir);
  }

/**
 * @brief Set ring mute option.
 *
 * @param [in] bMute true to mute ring.
 *
 * @retval ZOK Set ring mute option successfully.
 * @retval ZFAILED Set ring mute option failed.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetRingMute
 */
  public static int Mtc_ProvDbSetRingMute(boolean bMute) {
    return MtcProvDbJNI.Mtc_ProvDbSetRingMute(bMute);
  }

/**
 * @brief Set default temporary directory.
 *
 * @param [in] pcDir The default temporary directory.
 *
 * @retval ZOK Set the default temporary directory successfully.
 * @retval ZFAILED Set the default temporary directory failed.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetTempDir
 */
  public static int Mtc_ProvDbSetTempDir(String pcDir) {
    return MtcProvDbJNI.Mtc_ProvDbSetTempDir(pcDir);
  }

/**
 * @brief Get archive server address.
 *
 * @return Archive server address.
 */
  public static String Mtc_ProvDbGetAcvAddr() {
    return MtcProvDbJNI.Mtc_ProvDbGetAcvAddr();
  }

/**
 * @brief Get archive server port.
 *
 * @return Archive server port.
 */
  public static int Mtc_ProvDbGetAcvPort() {
    return MtcProvDbJNI.Mtc_ProvDbGetAcvPort();
  }

/**
 * @brief Get archive server url.
 *
 * @return Archive server url.
 */
  public static String Mtc_ProvDbGetAcvUrl() {
    return MtcProvDbJNI.Mtc_ProvDbGetAcvUrl();
  }

/**
 * @brief Set archive server info.
 *
 * @param [in] pcAddr The archive server address.
 * @param [in] wPort The archive server port.
 * @param [in] pcUrl The archive server url.
 *
 * @retval ZOK Set archive server info successfully.
 * @retval ZFAILED Set archive server info failed.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetAcvAddr, @ref MtcProvDb::Mtc_ProvDbGetAcvPort, @ref MtcProvDb::Mtc_ProvDbGetAcvUrl
 */
  public static int Mtc_ProvDbSetAcvServer(String pcAddr, int wPort, String pcUrl) {
    return MtcProvDbJNI.Mtc_ProvDbSetAcvServer(pcAddr, wPort, pcUrl);
  }

/**
 * @brief Get extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [out] ppcParm The parameter value.
 *
 * @retval ZOK get extension parameter successfully.
 * @retval ZFAILED get extension parameter failed, 
 *                 the extension parameter is not exist.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbSetExtnParm
 */
  public static int Mtc_ProvDbGetExtnParm(String pcName, MtcString ppcParm) {
    return MtcProvDbJNI.Mtc_ProvDbGetExtnParm(pcName, ppcParm);
  }

/**
 * @brief Get extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [out] pbParm The parameter value.
 *
 * @retval ZOK get extension parameter successfully.
 * @retval ZFAILED get extension parameter failed, 
 *                 the extension parameter is not exist.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetExtnParm
 */
  public static int Mtc_ProvDbGetExtnParmBool(String pcName, MtcNumber pbParm) {
    return MtcProvDbJNI.Mtc_ProvDbGetExtnParmBool(pcName, pbParm);
  }

/**
 * @brief Get extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [out] piParm The parameter value.
 *
 * @retval ZOK get extension parameter successfully.
 * @retval ZFAILED get extension parameter failed, 
 *                 the extension parameter is not exist.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetExtnParm
 */
  public static int Mtc_ProvDbGetExtnParmInt(String pcName, MtcNumber piParm) {
    return MtcProvDbJNI.Mtc_ProvDbGetExtnParmInt(pcName, piParm);
  }

/**
 * @brief Get extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [out] piParm The parameter value.
 *
 * @retval ZOK get extension parameter successfully.
 * @retval ZFAILED get extension parameter failed, 
 *                 the extension parameter is not exist.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetExtnParm
 */
  public static int Mtc_ProvDbGetExtnParmUint(String pcName, MtcNumber piParm) {
    return MtcProvDbJNI.Mtc_ProvDbGetExtnParmUint(pcName, piParm);
  }

/**
 * @brief Get extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [in] iIndex The parameter index.
 *
 * @return The parameter value when get extension parameter successfully, 
 *              otherwise return empty string.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbSetExtnParm
 */
  public static String Mtc_ProvDbGetExtnParmX(String pcName, int iIndex) {
    return MtcProvDbJNI.Mtc_ProvDbGetExtnParmX(pcName, iIndex);
  }

/**
 * @brief Get extension parameter.
 *
 * @param [in] pcName The parameter name.
 *
 * @retval ZOK Get the parameter count successfully.
 * @retval ZFAILED Get the parameter count failed.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbSetExtnParm
 */
  public static int Mtc_ProvDbGetExtnParmCount(String pcName) {
    return MtcProvDbJNI.Mtc_ProvDbGetExtnParmCount(pcName);
  }

/**
 * @brief Set extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [in] pcVal The parameter value.
 *
 * @retval ZOK Set the parameter successfully.
 * @retval ZFAILED Set the parameter failed.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetExtnParm
 */
  public static int Mtc_ProvDbSetExtnParm(String pcName, String pcVal) {
    return MtcProvDbJNI.Mtc_ProvDbSetExtnParm(pcName, pcVal);
  }

/**
 * @brief Set extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [in] bVal The parameter value.
 *
 * @retval ZOK Set the parameter successfully.
 * @retval ZFAILED Set the parameter failed.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetExtnParm
 */
  public static int Mtc_ProvDbSetExtnParmBool(String pcName, boolean bVal) {
    return MtcProvDbJNI.Mtc_ProvDbSetExtnParmBool(pcName, bVal);
  }

/**
 * @brief Set extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [in] iVal The parameter value.
 *
 * @retval ZOK Set the parameter successfully.
 * @retval ZFAILED Set the parameter failed.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetExtnParm
 */
  public static int Mtc_ProvDbSetExtnParmInt(String pcName, int iVal) {
    return MtcProvDbJNI.Mtc_ProvDbSetExtnParmInt(pcName, iVal);
  }

/**
 * @brief Set extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [in] iVal The parameter value.
 *
 * @retval ZOK Set the parameter successfully.
 * @retval ZFAILED Set the parameter failed.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetExtnParm
 */
  public static int Mtc_ProvDbSetExtnParmUint(String pcName, int iVal) {
    return MtcProvDbJNI.Mtc_ProvDbSetExtnParmUint(pcName, iVal);
  }

/**
 * @brief Add extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [in] pcVal The parameter value.
 *
 * @retval ZOK Add the parameter successfully.
 * @retval ZFAILED Add the parameter failed.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetExtnParm
 */
  public static int Mtc_ProvDbAddExtnParm(String pcName, String pcVal) {
    return MtcProvDbJNI.Mtc_ProvDbAddExtnParm(pcName, pcVal);
  }

/**
 * @brief Add extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [in] wNameLen The parameter name length.
 * @param [in] pcVal The parameter value.
 * @param [in] wValLen The parameter value length.
 *
 * @retval ZOK Add the parameter successfully.
 * @retval ZFAILED Add the parameter failed.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetExtnParm
 */
  public static int Mtc_ProvDbAddExtnParmN(String pcName, int wNameLen, String pcVal, int wValLen) {
    return MtcProvDbJNI.Mtc_ProvDbAddExtnParmN(pcName, wNameLen, pcVal, wValLen);
  }

/**
 * @brief Remove extension parameter.
 *
 * @param [in] pcName The parameter name.
 *
 * @retval ZOK Remove the parameter successfully.
 * @retval ZFAILED Remove the parameter failed.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetExtnParm
 */
  public static int Mtc_ProvDbRmvExtnParm(String pcName) {
    return MtcProvDbJNI.Mtc_ProvDbRmvExtnParm(pcName);
  }

/**
 * @brief Remove extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [in] wNameLen The parameter name length.
 *
 * @retval ZOK Remove the parameter successfully.
 * @retval ZFAILED Remove the parameter failed.
 *
 * @see @ref MtcProvDb::Mtc_ProvDbGetExtnParm
 */
  public static int Mtc_ProvDbRmvExtnParmN(String pcName, int wNameLen) {
    return MtcProvDbJNI.Mtc_ProvDbRmvExtnParmN(pcName, wNameLen);
  }

}
