/**
 * @file MtcProfDb.java
 * @brief MtcProfDb interface
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

/**
 * @brief MtcProfDb interface
 */
public class MtcProfDb implements MtcProfDbConstants {
/**
 * @brief Get application version from database.
 *
 * @return Application version.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbSetAppVer
 */
  public static String Mtc_ProfDbGetAppVer() {
    return MtcProfDbJNI.Mtc_ProfDbGetAppVer();
  }

/**
 * @brief Set application version from database.
 *
 * @param [in] pcAppVer The application version.
 *
 * @retval ZOK Set application version successfully.
 * @retval ZFAILED Set application version failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetAppVer
 */
  public static int Mtc_ProfDbSetAppVer(String pcAppVer) {
    return MtcProfDbJNI.Mtc_ProfDbSetAppVer(pcAppVer);
  }

/**
 * @brief Get remember password option from database.
 *
 * @retval true Remember password.
 * @retval false Do not remember password.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbSetRemPwd
 */
  public static boolean Mtc_ProfDbGetRemPwd() {
    return MtcProfDbJNI.Mtc_ProfDbGetRemPwd();
  }

/**
 * @brief Set remember password option.
 *
 * @param [in] bRember The option of remembering password.
 *
 * @retval ZOK Set remember password option successfully.
 * @retval ZFAILED Set remember password option failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetRemPwd
 */
  public static int Mtc_ProfDbSetRemPwd(boolean bRember) {
    return MtcProfDbJNI.Mtc_ProfDbSetRemPwd(bRember);
  }

/**
 * @brief Get the user automatically login option from database.
 *
 * @retval true User will automatically login.
 * @retval false User will not automatically login.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbSetAutoLogin
*/
  public static boolean Mtc_ProfDbGetAutoLogin() {
    return MtcProfDbJNI.Mtc_ProfDbGetAutoLogin();
  }

/**
 * @brief Set the user automatically login option.
 *
 * @param [in] bAuto User automatically login option.
 *
 * @retval ZOK Set the option successfully.
 * @retval ZFAILED Set the option option failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetAutoLogin
 */
  public static int Mtc_ProfDbSetAutoLogin(boolean bAuto) {
    return MtcProfDbJNI.Mtc_ProfDbSetAutoLogin(bAuto);
  }

/**
 * @brief Get avatar file name.
 *
 * @return The string of avatar file name.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbSetAvatarFile
 */
  public static String Mtc_ProfDbGetAvatarFile() {
    return MtcProfDbJNI.Mtc_ProfDbGetAvatarFile();
  }

/**
 * @brief Set avatar file name.
 *
 * @param [in] pcFileName Avatar file name.
 *
 * @retval ZOK Set avatar file name successfully.
 * @retval ZFAILED Set avatar file name failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetAvatarFile
 */
  public static int Mtc_ProfDbSetAvatarFile(String pcFileName) {
    return MtcProfDbJNI.Mtc_ProfDbSetAvatarFile(pcFileName);
  }

/**
 * @brief Get country code.
 *
 * @return The string of country code.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbSetCountryCode
 */
  public static String Mtc_ProfDbGetCountryCode() {
    return MtcProfDbJNI.Mtc_ProfDbGetCountryCode();
  }

/**
 * @brief Set country code.
 *
 * @param [in] pcCountryCode Country code.
 *
 * @retval ZOK Set country code successfully.
 * @retval ZFAILED Set country code failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetCountryCode
 */
  public static int Mtc_ProfDbSetCountryCode(String pcCountryCode) {
    return MtcProfDbJNI.Mtc_ProfDbSetCountryCode(pcCountryCode);
  }

/**
 * @brief Get the client provisioning enable from database.
 *
 * @retval true Start client provisioning.
 * @retval false Do not start client provisioning.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbSetCpEnable
*/
  public static boolean Mtc_ProfDbGetCpEnable() {
    return MtcProfDbJNI.Mtc_ProfDbGetCpEnable();
  }

/**
 * @brief Set client provisioning enable.
 *
 * @param [in] bCpEnable The client provisioning option.
 *
 * @retval ZOK Set the client provisioning option successfully.
 * @retval ZFAILED Set the client provisioning option failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetCpEnable
 */
  public static int Mtc_ProfDbSetCpEnable(boolean bCpEnable) {
    return MtcProfDbJNI.Mtc_ProfDbSetCpEnable(bCpEnable);
  }

/**
 * @brief Get extension parameter.
 *
 * @param [in] pcName The parameter name.
 *
 * @retval ZNULL if no parameter which do not exist, or the parameter value.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbSetExtParm
 */
  public static String Mtc_ProfDbGetExtParm(String pcName) {
    return MtcProfDbJNI.Mtc_ProfDbGetExtParm(pcName);
  }

/**
 * @brief Set extension parameter.
 *
 * @param [in] pcName The parameter name.
 * @param [in] pcVal The parameter value.
 *
 * @retval ZOK Set the parameter successfully.
 * @retval ZFAILED Set the parameter failed.
 *
 * @see @ref MtcProfDb::Mtc_ProfDbGetExtParm
 */
  public static int Mtc_ProfDbSetExtParm(String pcName, String pcValue) {
    return MtcProfDbJNI.Mtc_ProfDbSetExtParm(pcName, pcValue);
  }

}
