/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

public class MtcProfDbJNI {
    public final static void MtcNumber_value_set(long jarg1, MtcNumber jarg1_, int jarg2) {

    }

    public final static int MtcNumber_value_get(long jarg1, MtcNumber jarg1_) {
        return 0;
    }

    public final static long new_MtcNumber() {
        return 0;

    }

    public final static void delete_MtcNumber(long jarg1) {

    }

    public final static void MtcByteArray_data_set(long jarg1, MtcByteArray jarg1_, long jarg2) {

    }

    public final static long MtcByteArray_data_get(long jarg1, MtcByteArray jarg1_) {
        return 0;

    }

    public final static void MtcByteArray_size_set(long jarg1, MtcByteArray jarg1_, long jarg2) {

    }

    public final static long MtcByteArray_size_get(long jarg1, MtcByteArray jarg1_) {
        return 0;

    }

    public final static void MtcByteArray_value_set(long jarg1, MtcByteArray jarg1_, byte[] jarg2) {

    }

    public final static byte[] MtcByteArray_value_get(long jarg1, MtcByteArray jarg1_) {
        return null;

    }

    public final static long new_MtcByteArray() {
        return 0;

    }

    public final static void delete_MtcByteArray(long jarg1) {

    }

    public final static void MtcString_value_set(long jarg1, MtcString jarg1_, String jarg2) {

    }

    public final static String MtcString_value_get(long jarg1, MtcString jarg1_) {
        return null;

    }

    public final static long new_MtcString() {
        return 0;

    }

    public final static void delete_MtcString(long jarg1) {

    }

    public final static String Mtc_ProfDbGetAppVer() {
        return null;

    }

    public final static int Mtc_ProfDbSetAppVer(String jarg1) {
        return 0;

    }

    public final static boolean Mtc_ProfDbGetRemPwd() {
        return false;
    }

    public final static int Mtc_ProfDbSetRemPwd(boolean jarg1) {
        return 0;
    }

    public final static boolean Mtc_ProfDbGetAutoLogin() {
        return false;

    }

    public final static int Mtc_ProfDbSetAutoLogin(boolean jarg1) {
        return 0;

    }

    public final static String Mtc_ProfDbGetAvatarFile() {
        return null;

    }

    public final static int Mtc_ProfDbSetAvatarFile(String jarg1) {
        return 0;

    }

    public final static String Mtc_ProfDbGetCountryCode() {
        return null;

    }

    public final static int Mtc_ProfDbSetCountryCode(String jarg1) {
        return 0;

    }

    public final static boolean Mtc_ProfDbGetCpEnable() {
        return false;
    }

    public final static int Mtc_ProfDbSetCpEnable(boolean jarg1) {
        return 0;

    }

    public final static String Mtc_ProfDbGetExtParm(String jarg1) {
        return null;
    }

    public final static int Mtc_ProfDbSetExtParm(String jarg1, String jarg2) {
        return 0;

    }
}
