/**
 * @file MtcProfConstants.java
 * @brief MtcProfConstants constants
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

/**
 * @brief MtcProfConstants constants
 */
public interface MtcProfConstants {
  public final static int INVALIDID = -1; /**< @brief invalid id */
  public final static int ZOK = 0; /**< @brief ok */
  public final static int ZFAILED = 1; /**< @brief failed */
  public final static int MTC_PROV_MEDIA_MASK = 0xFf;
  public final static int MTC_PROV_SERVICE_MASK = 0xFF00;
  // EN_MTC_PROF_MEDIA_MODE 
  public final static int EN_MTC_PROF_MEDIA_BASE = 0x00; /**< @brief media base */
  public final static int EN_MTC_PROF_MEDIA_ENHANCE = 0x01; /**< @brief media enhance */

  // EN_MTC_PROF_SERVICE_MODE 
  public final static int EN_MTC_PROF_SERVICE_VOIP = 0x0000; /**< @brief voip service */
  public final static int EN_MTC_PROF_SERVICE_MMTEL = 0x0100; /**< @brief mmtel service */
  public final static int EN_MTC_PROF_SERVICE_RCS5 = 0x0200; /**< @brief rcs5 service */
  public final static int EN_MTC_PROF_SERVICE_JOYN_HF = 0x0400; /**< @brief joyn HF service */
  public final static int EN_MTC_PROF_SERVICE_JOYN_BB = 0x0800; /**< @brief joyn BB service */

}
