/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

public interface MtcProvCfgConstants {
  public final static int INVALIDID = -1;
  public final static int ZOK = 0;
  public final static int ZFAILED = 1;
}
