/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

public class MtcRingJNI {
    public final static void MtcNumber_value_set(long jarg1, MtcNumber jarg1_, int jarg2) {

    }

    public final static int MtcNumber_value_get(long jarg1, MtcNumber jarg1_) {
        return 0;

    }

    public final static long new_MtcNumber() {
        return 0;

    }

    public final static void delete_MtcNumber(long jarg1) {

    }

    public final static void MtcByteArray_data_set(long jarg1, MtcByteArray jarg1_, long jarg2) {

    }

    public final static long MtcByteArray_data_get(long jarg1, MtcByteArray jarg1_) {
        return 0;

    }

    public final static void MtcByteArray_size_set(long jarg1, MtcByteArray jarg1_, long jarg2) {

    }

    public final static long MtcByteArray_size_get(long jarg1, MtcByteArray jarg1_) {
        return 0;

    }

    public final static void MtcByteArray_value_set(long jarg1, MtcByteArray jarg1_, byte[] jarg2) {

    }

    public final static byte[] MtcByteArray_value_get(long jarg1, MtcByteArray jarg1_) {
        return null;
    }

    public final static long new_MtcByteArray() {
        return 0;

    }

    public final static void delete_MtcByteArray(long jarg1) {

    }

    public final static void MtcString_value_set(long jarg1, MtcString jarg1_, String jarg2) {

    }

    public final static String MtcString_value_get(long jarg1, MtcString jarg1_) {
        return null;
    }

    public final static long new_MtcString() {
        return 0;

    }

    public final static void delete_MtcString(long jarg1) {

    }

    public final static int Mtc_RingPlay(int jarg1, int jarg2) {
        return 0;

    }

    public final static int Mtc_RingPlayNoLoop(int jarg1) {
        return 0;
    }

    public final static int Mtc_RingPlayX(String jarg1, int jarg2) {
        return 0;
    }

    public final static void Mtc_RingStop(int jarg1) {

    }

    public final static boolean Mtc_RingIsPlay() {
        return false;
    }

    public final static boolean Mtc_RingGetMute() {
        return false;
    }

    public final static int Mtc_RingSetMute(boolean jarg1) {
        return 0;
    }

    public final static boolean Mtc_RingGetMuteType(int jarg1) {
        return false;
    }

    public final static int Mtc_RingSetMuteType(int jarg1, boolean jarg2) {
        return 0;
    }

    public final static String Mtc_RingGetName(int jarg1) {
        return null;

    }

    public final static String Mtc_RingGetDesc(int jarg1) {
        return null;

    }

    public final static int Mtc_RingGetType(String jarg1) {
        return 0;
    }

    public final static String Mtc_RingGetCtmName(int jarg1) {
        return null;

    }

    public final static int Mtc_RingSetCtmName(int jarg1, String jarg2) {
        return 0;
    }

    public final static String Mtc_RingGetDir() {
        return null;
    }

    public final static void Mtc_RingSetDir(String jarg1, int jarg2) {

    }
}
