/**
 * @file MtcUriConstants.java
 * @brief MtcUriConstants constants
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

/**
 * @brief MtcUriConstants constants
 */
public interface MtcUriConstants {
  public final static int INVALIDID = -1; /**< @brief invalid id */
  public final static int ZOK = 0; /**< @brief ok */
  public final static int ZFAILED = 1; /**< @brief failed */
  public final static int MTC_URI_FMT_NOT_COMPLTE = -1; /**< @brief URI is not complete */
  public final static int MTC_URI_FMT_INVAL_URI = -2; /**< @brief URI is invalid format */
  public final static int MTC_URI_FMT_EMPTY_URI = -3; /**< @brief URI is empty */
}
