/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

public class MtcUtilJNI {
    public final static void MtcNumber_value_set(long jarg1, MtcNumber jarg1_, int jarg2) {

    }



    public final static int MtcNumber_value_get(long jarg1, MtcNumber jarg1_) {
        return 0;

    }



    public final static long new_MtcNumber() {
        return 0;

    }



    public final static void delete_MtcNumber(long jarg1) {

    }



    public final static void MtcByteArray_data_set(long jarg1, MtcByteArray jarg1_, long jarg2) {

    }



    public final static long MtcByteArray_data_get(long jarg1, MtcByteArray jarg1_) {
        return 0;

    }



    public final static void MtcByteArray_size_set(long jarg1, MtcByteArray jarg1_, long jarg2) {

    }



    public final static long MtcByteArray_size_get(long jarg1, MtcByteArray jarg1_) {
        return 0;

    }



    public final static void MtcByteArray_value_set(long jarg1, MtcByteArray jarg1_, byte[] jarg2) {

    }



    public final static byte[] MtcByteArray_value_get(long jarg1, MtcByteArray jarg1_) {
        return null;
    }



    public final static long new_MtcByteArray() {
        return 0;

    }



    public final static void delete_MtcByteArray(long jarg1) {

    }


    public final static void MtcString_value_set(long jarg1, MtcString jarg1_, String jarg2) {

    }



    public final static String MtcString_value_get(long jarg1, MtcString jarg1_) {
        return null;
    }



    public final static long new_MtcString() {
        return 0;

    }



    public final static void delete_MtcString(long jarg1) {

    }



    public final static void ST_MTC_SYS_TIME_wYear_set(long jarg1, ST_MTC_SYS_TIME jarg1_, int jarg2) {

    }



    public final static int ST_MTC_SYS_TIME_wYear_get(long jarg1, ST_MTC_SYS_TIME jarg1_) {
        return 0;

    }



    public final static void ST_MTC_SYS_TIME_ucMonth_set(long jarg1, ST_MTC_SYS_TIME jarg1_, short jarg2) {

    }



    public final static short ST_MTC_SYS_TIME_ucMonth_get(long jarg1, ST_MTC_SYS_TIME jarg1_) {
        return 0;

    }



    public final static void ST_MTC_SYS_TIME_ucDay_set(long jarg1, ST_MTC_SYS_TIME jarg1_, short jarg2) {

    }



    public final static short ST_MTC_SYS_TIME_ucDay_get(long jarg1, ST_MTC_SYS_TIME jarg1_) {
        return 0;

    }



    public final static void ST_MTC_SYS_TIME_ucWeekDay_set(long jarg1, ST_MTC_SYS_TIME jarg1_, short jarg2) {

    }



    public final static short ST_MTC_SYS_TIME_ucWeekDay_get(long jarg1, ST_MTC_SYS_TIME jarg1_) {
        return 0;

    }



    public final static void ST_MTC_SYS_TIME_ucHour_set(long jarg1, ST_MTC_SYS_TIME jarg1_, short jarg2) {

    }



    public final static short ST_MTC_SYS_TIME_ucHour_get(long jarg1, ST_MTC_SYS_TIME jarg1_) {
        return 0;

    }



    public final static void ST_MTC_SYS_TIME_ucMinute_set(long jarg1, ST_MTC_SYS_TIME jarg1_, short jarg2) {

    }



    public final static short ST_MTC_SYS_TIME_ucMinute_get(long jarg1, ST_MTC_SYS_TIME jarg1_) {
        return 0;

    }



    public final static void ST_MTC_SYS_TIME_ucSecond_set(long jarg1, ST_MTC_SYS_TIME jarg1_, short jarg2) {

    }


    public final static short ST_MTC_SYS_TIME_ucSecond_get(long jarg1, ST_MTC_SYS_TIME jarg1_) {
        return 0;

    }



    public final static void ST_MTC_SYS_TIME_iTzOffset_set(long jarg1, ST_MTC_SYS_TIME jarg1_, int jarg2) {

    }



    public final static int ST_MTC_SYS_TIME_iTzOffset_get(long jarg1, ST_MTC_SYS_TIME jarg1_) {
        return 0;

    }



    public final static long new_ST_MTC_SYS_TIME() {
        return 0;

    }



    public final static void delete_ST_MTC_SYS_TIME(long jarg1) {

    }



    public final static void Mtc_AnyLogErrStr(String jarg1, String jarg2) {

    }



    public final static void Mtc_AnyLogInfoStr(String jarg1, String jarg2) {

    }



    public final static void Mtc_AnyLogDbgStr(String jarg1, String jarg2) {

    }



    public final static int Mtc_GetLclIpCnt() {
        return 0;

    }



    public final static String Mtc_GetLclIp(int jarg1) {
        return null;

    }

    public final static int Mtc_GetAccessNetType() {
        return 0;

    }



    public final static int Mtc_TimerCreate(Object jarg1, boolean jarg2, long jarg3, MtcNumber jarg4) {
        return 0;

    }



    public final static int Mtc_TimerDelete(int jarg1) {
        return 0;

    }



    public final static int Mtc_TimerStart(int jarg1, int jarg2) {
        return 0;

    }



    public final static int Mtc_TimerStop(int jarg1) {
        return 0;

    }



    public final static boolean Mtc_TimerIsRun(int jarg1) {
        return false;
    }



    public final static int Mtc_TimerSchedule(Object jarg1, long jarg2, int jarg3) {
        return 0;

    }



    public final static int Mtc_Time2SysTime(int jarg1, long jarg2, ST_MTC_SYS_TIME jarg2_) {
        return 0;

    }



    public final static int Mtc_SysTime2Time(long jarg1, ST_MTC_SYS_TIME jarg1_, MtcNumber jarg2) {
        return 0;

    }



    public final static int Mtc_CmdRun(String jarg1) {
        return 0;

    }



    public final static int Mtc_PerformOnMainThread(long jarg1, int jarg2) {
        return 0;
    }


}
