/**
 * @file MtcUtil.java
 * @brief MtcUtil interface
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

/**
 * @brief MtcUtil interface
 */
public class MtcUtil implements MtcUtilConstants {
/**
 * @brief Print ERROR log with format string information.
 * User can specific log name as the log module prefix
 * Log print level can be set by Mtc_CliDbSetLogLevel.
 *
 * @param [in] pcLogName The log name. Default name is "ZOS" if no log name.
 * @param [in] pcFormat String format.
 * @param [in] ... String vars.
 *
 * @see @ref MtcUtil::Mtc_AnyLogInfoStr
 */
  public static void Mtc_AnyLogErrStr(String pcLogName, String pcFormat) {
    MtcUtilJNI.Mtc_AnyLogErrStr(pcLogName, pcFormat);
  }

/**
 * @brief Print INFO log with format string information.
 * User can specific log name as the log module prefix
 * Log print level can be set by Mtc_CliDbSetLogLevel.
 *
 * @param [in] pcLogName The log name. Default name is "ZOS" if no log name.
 * @param [in] pcFormat String format.
 * @param [in] ... String vars.
 *
 * @see @ref MtcUtil::Mtc_AnyLogErrStr
 */
  public static void Mtc_AnyLogInfoStr(String pcLogName, String pcFormat) {
    MtcUtilJNI.Mtc_AnyLogInfoStr(pcLogName, pcFormat);
  }

/**
 * @brief Print DEBUG log with format string information.
 * User can specific log name as the log module prefix
 * Log print level can be set by Mtc_DbSetLogLevel.
 *
 * @param [in] pcLogName The log name. Default name is "ZOS" if no log name.
 * @param [in] pcFormat String format.
 * @param [in] ... String vars.
 *
 * @see @ref MtcUtil::Mtc_AnyLogInfoStr
 */
  public static void Mtc_AnyLogDbgStr(String pcLogName, String pcFormat) {
    MtcUtilJNI.Mtc_AnyLogDbgStr(pcLogName, pcFormat);
  }

/**
 * @brief Get local ip count.
 *
 * @return Local ip count successfully, otherwise retrun 0.
 *
 * @see @ref MtcUtil::Mtc_GetLclIp
 */
  public static int Mtc_GetLclIpCnt() {
    return MtcUtilJNI.Mtc_GetLclIpCnt();
  }

/**
 * @brief Get local ip.
 *
 * @param [in] iIndex Local ip index.
 *
 * @return Local ip successfully, otherwise return loopback address.
 *    the caller must copy it, then use.
 *
 * @see @ref MtcUtil::Mtc_GetLclIpCnt
 */
  public static String Mtc_GetLclIp(int iIndex) {
    return MtcUtilJNI.Mtc_GetLclIp(iIndex);
  }

/**
 * @brief Get access network type.
 *
 * @return Access network type successfully, 
 * otherwise return MTC_ANET_UNKNOWN.
 */
  public static int Mtc_GetAccessNetType() {
    return MtcUtilJNI.Mtc_GetAccessNetType();
  }

/**
 * @brief Create a new timer.
 *
 * @param [in] zCookie User defined cookie value.
 * @param [in] bCycle Timer mode, cycle or once a time.
 * @param [in] pfnActive Timer active callback.
 * @param [out] pzTimerId Timer ID.
 *
 * @retval ZOK Timer create successfully.
 * @retval ZFAILED Timer create failed.
 *
 * @see @ref MtcUtil::Mtc_TimerDelete
 */
  public static int Mtc_TimerCreate(Object zCookie, boolean bCycle, SWIGTYPE_p_f_unsigned_long_unsigned_long__void pfnActive, MtcNumber pzTimerId) {
    return MtcUtilJNI.Mtc_TimerCreate(zCookie, bCycle, SWIGTYPE_p_f_unsigned_long_unsigned_long__void.getCPtr(pfnActive), pzTimerId);
  }

/**
 * @brief Delete a timer.
 *
 * @param [in] zTimerId Timer ID.
 *
 * @retval ZOK Timer delete successfully.
 * @retval ZFAILED Timer delete failed.
 *
 * @see @ref MtcUtil::Mtc_TimerCreate
 */
  public static int Mtc_TimerDelete(int zTimerId) {
    return MtcUtilJNI.Mtc_TimerDelete(zTimerId);
  }

/**
 * @brief Start a timer.
 *
 * @param [in] zTimerId Timer ID.
 * @param [in] dwTimeLen Time interval in milliseconds.
 *
 * @retval ZOK Timer start successfully.
 * @retval ZFAILED Timer start failed.
 *
 * @note Timer must not in running state.
 *
 * @see @ref MtcUtil::Mtc_TimerStop
 */
  public static int Mtc_TimerStart(int zTimerId, int dwTimeLen) {
    return MtcUtilJNI.Mtc_TimerStart(zTimerId, dwTimeLen);
  }

/**
 * @brief Stop a timer.
 *
 * @param [in] zTimerId Timer ID.
 *
 * @retval ZOK Timer stop successfully.
 * @retval ZFAILED Timer stop failed.
 *
 * @see @ref MtcUtil::Mtc_TimerStart
 */
  public static int Mtc_TimerStop(int zTimerId) {
    return MtcUtilJNI.Mtc_TimerStop(zTimerId);
  }

/**
 * @brief Check if a timer is running.
 *
 * @param [in] zTimerId Timer ID.
 *
 * @retval true Timer has been started and still in counting.
 * @retval false Otherwise.
 *
 * @see @ref MtcUtil::Mtc_TimerStart
 */
  public static boolean Mtc_TimerIsRun(int zTimerId) {
    return MtcUtilJNI.Mtc_TimerIsRun(zTimerId);
  }

/**
 * @brief Schedule a new timer after some seconds.
 *
 * @param [in] zCookie User defined cookie.
 * @param [in] pfnSchedule User defined schedule callback.
 * @param [in] dwTimeLen Time interval in milliseconds.
 *
 * @retval ZOK Timer start successfully.
 * @retval ZFAILED Timer start failed.
 *
 * @note Timer must not in running state.
 *
 * @see @ref MtcUtil::Mtc_TimerCreate
 */
  public static int Mtc_TimerSchedule(Object zCookie, SWIGTYPE_p_f_unsigned_long__void pfnSchedule, int dwTimeLen) {
    return MtcUtilJNI.Mtc_TimerSchedule(zCookie, SWIGTYPE_p_f_unsigned_long__void.getCPtr(pfnSchedule), dwTimeLen);
  }

/**
 * @brief Convert time value from ZTIME_T to ST_MTC_SYS_TIME structure.
 *
 * @param [in] zTime Time value.
 * @param [out] pstTime Time value in ST_MTC_SYS_TIME structure.
 *
 * @retval ZOK Convert successfully.
 * @retval ZFAILED Convert failed.
 *
 * @see
 */
  public static int Mtc_Time2SysTime(int zTime, ST_MTC_SYS_TIME pstTime) {
    return MtcUtilJNI.Mtc_Time2SysTime(zTime, ST_MTC_SYS_TIME.getCPtr(pstTime), pstTime);
  }

/**
 * @brief Convert time value from ST_MTC_SYS_TIME structure to ZTIME_T.
 *
 * @param [in] pstTime Time value in ST_MTC_SYS_TIME structure.
 * @param [out] pzTime Time value in ZTIME_T structure.
 *
 * @retval ZOK Convert successfully.
 * @retval ZFAILED Convert failed.
 *
 * @see
 */
  public static int Mtc_SysTime2Time(ST_MTC_SYS_TIME pstTime, MtcNumber pzTime) {
    return MtcUtilJNI.Mtc_SysTime2Time(ST_MTC_SYS_TIME.getCPtr(pstTime), pstTime, pzTime);
  }

/**
 * @brief Run debug command.
 *
 * @param [in] pcCmd Command string.
 *
 * @retval ZOK Run command successfully.
 * @retval ZFAILED Run command failed.
 *
 * @see
 */
  public static int Mtc_CmdRun(String pcCmd) {
    return MtcUtilJNI.Mtc_CmdRun(pcCmd);
  }

/**
 * @brief Perform function on main thread.
 *
 * @param [in] pfnFunc Function to perform.
 * @param [in] zEvntId Event ID.
 *
 * @retval ZOK Run command successfully.
 * @retval ZFAILED Run command failed.
 *
 * @see
 */
  public static int Mtc_PerformOnMainThread(SWIGTYPE_p_f_p_void__void pfnFunc, int zEvntId) {
    return MtcUtilJNI.Mtc_PerformOnMainThread(SWIGTYPE_p_f_p_void__void.getCPtr(pfnFunc), zEvntId);
  }

}
