/**
 * @file MtcVer.java
 * @brief MtcVer interface
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

/**
 * @brief MtcVer interface
 */
public class MtcVer implements MtcVerConstants {
/**
 * @brief MTC get client version.
 *
 * @return MTC version.
 */
  public static String Mtc_GetVersion() {
    return MtcVerJNI.Mtc_GetVersion();
  }

/**
 * @brief MTC get media engine version.
 *
 * @return Media engine version.
 */
  public static String Mtc_GetMmeVersion() {
    return MtcVerJNI.Mtc_GetMmeVersion();
  }

/**
 * @brief MTC get mmp version.
 *
 * @return mmp version.
 */
  public static int Mtc_GetMmpVersion() {
    return MtcVerJNI.Mtc_GetMmpVersion();
  }

/**
 * @brief MTC get avatar version.
 *
 * @return Avatar version.
 */
  public static String Mtc_GetAvatarVersion() {
    return MtcVerJNI.Mtc_GetAvatarVersion();
  }

/**
 * @brief MTC get melon version
 *
 * @return Melon version.
 */
  public static String Mtc_GetMelonVersion() {
    return MtcVerJNI.Mtc_GetMelonVersion();
  }

/**
 * @brief MTC get lemon version
 *
 * @return Lemon version.
 */
  public static String Mtc_GetLemonVersion() {
    return MtcVerJNI.Mtc_GetLemonVersion();
  }

}
