/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

public class ST_MTC_SYS_TIME {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ST_MTC_SYS_TIME(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ST_MTC_SYS_TIME obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MtcUtilJNI.delete_ST_MTC_SYS_TIME(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setWYear(int value) {
    MtcUtilJNI.ST_MTC_SYS_TIME_wYear_set(swigCPtr, this, value);
  }

  public int getWYear() {
    return MtcUtilJNI.ST_MTC_SYS_TIME_wYear_get(swigCPtr, this);
  }

  public void setUcMonth(short value) {
    MtcUtilJNI.ST_MTC_SYS_TIME_ucMonth_set(swigCPtr, this, value);
  }

  public short getUcMonth() {
    return MtcUtilJNI.ST_MTC_SYS_TIME_ucMonth_get(swigCPtr, this);
  }

  public void setUcDay(short value) {
    MtcUtilJNI.ST_MTC_SYS_TIME_ucDay_set(swigCPtr, this, value);
  }

  public short getUcDay() {
    return MtcUtilJNI.ST_MTC_SYS_TIME_ucDay_get(swigCPtr, this);
  }

  public void setUcWeekDay(short value) {
    MtcUtilJNI.ST_MTC_SYS_TIME_ucWeekDay_set(swigCPtr, this, value);
  }

  public short getUcWeekDay() {
    return MtcUtilJNI.ST_MTC_SYS_TIME_ucWeekDay_get(swigCPtr, this);
  }

  public void setUcHour(short value) {
    MtcUtilJNI.ST_MTC_SYS_TIME_ucHour_set(swigCPtr, this, value);
  }

  public short getUcHour() {
    return MtcUtilJNI.ST_MTC_SYS_TIME_ucHour_get(swigCPtr, this);
  }

  public void setUcMinute(short value) {
    MtcUtilJNI.ST_MTC_SYS_TIME_ucMinute_set(swigCPtr, this, value);
  }

  public short getUcMinute() {
    return MtcUtilJNI.ST_MTC_SYS_TIME_ucMinute_get(swigCPtr, this);
  }

  public void setUcSecond(short value) {
    MtcUtilJNI.ST_MTC_SYS_TIME_ucSecond_set(swigCPtr, this, value);
  }

  public short getUcSecond() {
    return MtcUtilJNI.ST_MTC_SYS_TIME_ucSecond_get(swigCPtr, this);
  }

  public void setITzOffset(int value) {
    MtcUtilJNI.ST_MTC_SYS_TIME_iTzOffset_set(swigCPtr, this, value);
  }

  public int getITzOffset() {
    return MtcUtilJNI.ST_MTC_SYS_TIME_iTzOffset_get(swigCPtr, this);
  }

  public ST_MTC_SYS_TIME() {
    this(MtcUtilJNI.new_ST_MTC_SYS_TIME(), true);
  }

}
