/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.lemon;

public class ST_MTC_RECT {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ST_MTC_RECT(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ST_MTC_RECT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MtcMediaJNI.delete_ST_MTC_RECT(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIX(int value) {
    MtcMediaJNI.ST_MTC_RECT_iX_set(swigCPtr, this, value);
  }

  public int getIX() {
    return MtcMediaJNI.ST_MTC_RECT_iX_get(swigCPtr, this);
  }

  public void setIY(int value) {
    MtcMediaJNI.ST_MTC_RECT_iY_set(swigCPtr, this, value);
  }

  public int getIY() {
    return MtcMediaJNI.ST_MTC_RECT_iY_get(swigCPtr, this);
  }

  public void setIWidth(int value) {
    MtcMediaJNI.ST_MTC_RECT_iWidth_set(swigCPtr, this, value);
  }

  public int getIWidth() {
    return MtcMediaJNI.ST_MTC_RECT_iWidth_get(swigCPtr, this);
  }

  public void setIHeight(int value) {
    MtcMediaJNI.ST_MTC_RECT_iHeight_set(swigCPtr, this, value);
  }

  public int getIHeight() {
    return MtcMediaJNI.ST_MTC_RECT_iHeight_get(swigCPtr, this);
  }

  public ST_MTC_RECT() {
    this(MtcMediaJNI.new_ST_MTC_RECT(), true);
  }

}
